#ifndef LIBP2P_BROWSER_SNAPSHOT_JS_H
#define LIBP2P_BROWSER_SNAPSHOT_JS_H
static const char kChengLibp2pBrowserSnapshotJS[] =
    "(function(){\n"
    "function signed(u){u=u>>>0;return u>2147483647?u-4294967296:u;}\n"
    "function argb(c){\n"
    "  if(!c||c==='transparent')return 0;\n"
    "  var m=c.match(/^rgba?\\(\\s*([\\d.]+)\\s*,\\s*([\\d.]+)\\s*,\\s*([\\d.]+)(?:\\s*,\\s*([\\d.]+))?\\s*\\)$/);\n"
    "  if(!m)return 0;\n"
    "  var r=+m[1]|0,g=+m[2]|0,b=+m[3]|0,a=m[4]==null?1:+m[4];\n"
    "  var ai=Math.round(a*255);\n"
    "  if(ai<=0)return 0;\n"
    "  if(ai>255)ai=255;\n"
    "  return signed((ai<<24)|(r<<16)|(g<<8)|b);\n"
    "}\n"
    "function mulA(color,op){\n"
    "  if(!color||op>=0.999)return color;\n"
    "  if(op<=0)return 0;\n"
    "  var u=color>>>0;\n"
    "  var a=Math.round(((u>>>24)&255)*op);\n"
    "  if(a<=0)return 0;\n"
    "  return signed((a<<24)|(u&0xffffff));\n"
    "}\n"
    "function px(s){var n=parseFloat(s);return isFinite(n)?Math.round(n):0;}\n"
    "function rad(st,w,h){\n"
    "  var s=st.borderTopLeftRadius||'0';\n"
    "  var n=parseFloat(s);\n"
    "  if(!isFinite(n)||n<=0)return 0;\n"
    "  if(String(s).indexOf('%')>=0){var m=w<h?w:h;return Math.round(m*n/100);}\n"
    "  return Math.round(n);\n"
    "}\n"
    "function weightOf(st){\n"
    "  var w=st.fontWeight;\n"
    "  if(w==='bold')return 700;\n"
    "  if(w==='normal')return 400;\n"
    "  var n=parseInt(w,10);\n"
    "  return isFinite(n)&&n>0?n:400;\n"
    "}\n"
    "function familyOf(st){\n"
    "  var f=st.fontFamily||'';\n"
    "  var m=f.match(/^[\"']?([^\"',]+)[\"']?/);\n"
    "  return m?m[1].trim():'';\n"
    "}\n"
    "function skipTag(t){\n"
    "  return t==='script'||t==='style'||t==='meta'||t==='link'||t==='head'||t==='noscript'||t==='template'||t==='br'||t==='wbr';\n"
    "}\n"
    "function esc(s){\n"
    "  s=String(s||'');\n"
    "  var o='';\n"
    "  for(var i=0;i<s.length;i++){\n"
    "    var ch=s.charAt(i);\n"
    "    if(ch==='%')o+='%25';\n"
    "    else if(ch==='\\n')o+='%0A';\n"
    "    else if(ch==='\\r')o+='%0D';\n"
    "    else o+=ch;\n"
    "  }\n"
    "  return o;\n"
    "}\n"
    "function intersect(a,b){\n"
    "  var x=Math.max(a.x,b.x), y=Math.max(a.y,b.y);\n"
    "  var r=Math.min(a.x+a.w,b.x+b.w), btm=Math.min(a.y+a.h,b.y+b.h);\n"
    "  return {x:x,y:y,w:Math.max(0,r-x),h:Math.max(0,btm-y)};\n"
    "}\n"
    "function isBlockingOverlay(st,r,vw,vh){\n"
    "  if(!st||!r) return false;\n"
    "  var pos=st.position;\n"
    "  if(pos!=='fixed'&&pos!=='absolute') return false;\n"
    "  if(r.width<vw*0.65||r.height<vh*0.65) return false;\n"
    "  var z=parseInt(st.zIndex,10);\n"
    "  if(!isFinite(z)) z=0;\n"
    "  var bg=argb(st.backgroundColor);\n"
    "  var a=(bg>>>24)&255;\n"
    "  if(pos==='fixed'&&(z>0||a>0)) return true;\n"
    "  if(a>0&&a<255) return true;\n"
    "  return false;\n"
    "}\n"
    "function visClip(b,clip,vw,vh){\n"
    "  if(b.w<=0||b.h<=0)return false;\n"
    "  if(b.x>=vw||b.y>=vh||b.x+b.w<=0||b.y+b.h<=0)return false;\n"
    "  if(clip.w<=0||clip.h<=0)return false;\n"
    "  var i=intersect(b,clip);\n"
    "  return i.w>0&&i.h>0;\n"
    "}\n"
    "function parseShadow(s){\n"
    "  var out={x:0,y:0,blur:0,spread:0,c:0};\n"
    "  if(!s||s==='none')return out;\n"
    "  var col=s.match(/rgba?\\([^)]+\\)/);\n"
    "  if(col) out.c=argb(col[0]);\n"
    "  var nums=s.match(/-?[\\d.]+px/g)||[];\n"
    "  if(nums.length>=1) out.x=px(nums[0]);\n"
    "  if(nums.length>=2) out.y=px(nums[1]);\n"
    "  if(nums.length>=3) out.blur=px(nums[2]);\n"
    "  if(nums.length>=4) out.spread=px(nums[3]);\n"
    "  return out;\n"
    "}\n"
    "function gradientFill(st){\n"
    "  var bi=st.backgroundImage||'';\n"
    "  if(bi==='none'||bi.indexOf('gradient')<0)return 0;\n"
    "  var m=bi.match(/rgba?\\(\\s*[\\d.]+(?:\\s*,\\s*[\\d.]+){2,3}\\s*\\)/);\n"
    "  return m?argb(m[0]):0;\n"
    "}\n"
    "function cssContent(raw){\n"
    "  if(!raw||raw==='none'||raw==='normal'||raw==='open-quote'||raw==='close-quote')return '';\n"
    "  var m=String(raw).match(/^['\"]([\\s\\S]*)['\"]$/);\n"
    "  var t=m?m[1]:'';\n"
    "  t=t.replace(/\\\\([0-9a-fA-F]{1,6})[ \\t]?/g,function(_,h){return String.fromCharCode(parseInt(h,16));});\n"
    "  return t;\n"
    "}\n"
    "function imgData(el){\n"
    "  try{\n"
    "    var tag=el.tagName?el.tagName.toLowerCase():'';\n"
    "    if(tag==='img'&&el.complete&&el.naturalWidth>0&&el.naturalHeight>0){\n"
    "      var c=document.createElement('canvas');\n"
    "      var iw=el.naturalWidth, ih=el.naturalHeight;\n"
    "      var max=2048, sc=Math.max(iw,ih);\n"
    "      if(sc>max){var k=max/sc; iw=Math.round(iw*k); ih=Math.round(ih*k);}\n"
    "      c.width=iw; c.height=ih;\n"
    "      c.getContext('2d').drawImage(el,0,0,iw,ih);\n"
    "      return c.toDataURL('image/png');\n"
    "    }\n"
    "    if(tag==='svg'||(el.namespaceURI&&String(el.namespaceURI).indexOf('svg')>=0)){\n"
    "      var ser=new XMLSerializer().serializeToString(el);\n"
    "      if(ser.indexOf('xmlns')<0) ser=ser.replace('<svg','<svg xmlns=\"http://www.w3.org/2000/svg\"');\n"
    "      return 'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(ser)));\n"
    "    }\n"
    "  }catch(e){}\n"
    "  return '';\n"
    "}\n"
    "function makeBox(k,t,x,y,w,h,bg,fg,fs,bw,bc,rr,href,typ,id,val,txt,fw,ff,img,sh,clip,z,opts){\n"
    "  return {k:k,t:t,x:x,y:y,w:w,h:h,bg:bg,fg:fg,fs:fs,bw:bw,bc:bc,rr:rr,href:href||'',typ:typ||'',id:id||'',val:val||'',txt:txt||'',fw:fw||400,ff:ff||'',img:img||'',sx:sh?sh.x:0,sy:sh?sh.y:0,sblur:sh?sh.blur:0,sspread:sh?sh.spread:0,sc:sh?sh.c:0,cx:clip.x,cy:clip.y,cw:clip.w,ch:clip.h,z:z||0,opts:opts||''};\n"
    "}\n"
    "function encOpts(opts){\n"
    "  var parts=[];\n"
    "  for(var i=0;i<opts.length;i++){\n"
    "    var v=String(opts[i].v||'').replace(/\\t/g,' ');\n"
    "    var t=String(opts[i].t||'').replace(/\\t/g,' ');\n"
    "    parts.push((opts[i].s?1:0)+'\\t'+v+'\\t'+t);\n"
    "  }\n"
    "  return parts.join('\\n');\n"
    "}\n"
    "function optionsOf(el){\n"
    "  var out=[], seen={};\n"
    "  function add(v,t,s){\n"
    "    v=String(v||'').replace(/\\s+/g,' ').trim();\n"
    "    t=String(t||'').replace(/\\s+/g,' ').trim();\n"
    "    if(!t) return;\n"
    "    if(!v) v=t;\n"
    "    var key=v+'|'+t;\n"
    "    if(seen[key]) return;\n"
    "    seen[key]=1;\n"
    "    out.push({v:v,t:t,s:s?1:0});\n"
    "  }\n"
    "  if(!el) return out;\n"
    "  if(el.tagName==='SELECT'){\n"
    "    for(var i=0;i<el.options.length;i++) add(el.options[i].value, el.options[i].text, el.options[i].selected);\n"
    "    return out;\n"
    "  }\n"
    "  var roots=[el];\n"
    "  var p=el.parentElement;\n"
    "  var depth=0;\n"
    "  while(p && depth<8){ roots.push(p); p=p.parentElement; depth++; }\n"
    "  var cid=el.getAttribute('aria-controls')||el.getAttribute('aria-owns');\n"
    "  if(cid){ var t=document.getElementById(cid); if(t) roots.push(t); }\n"
    "  for(var n=0;n<roots.length;n++){\n"
    "    var root=roots[n];\n"
    "    if(!root || !root.querySelectorAll) continue;\n"
    "    if(root.tagName==='SELECT'){\n"
    "      for(var i=0;i<root.options.length;i++) add(root.options[i].value, root.options[i].text, root.options[i].selected);\n"
    "    }\n"
    "    var sel=root.querySelector&&root.querySelector('select');\n"
    "    if(sel){\n"
    "      for(var i=0;i<sel.options.length;i++) add(sel.options[i].value, sel.options[i].text, sel.options[i].selected);\n"
    "    }\n"
    "    var opts=root.querySelectorAll('option, [role=option], .ng-option, .p-dropdown-item, [role=listbox] li');\n"
    "    for(var i=0;i<opts.length;i++){\n"
    "      var o=opts[i];\n"
    "      if(o.tagName==='SELECT') continue;\n"
    "      var lab=(o.getAttribute('aria-label')||o.textContent||'').replace(/\\s+/g,' ').trim();\n"
    "      if(!lab) continue;\n"
    "      var v=o.getAttribute('data-value')||o.getAttribute('value')||lab;\n"
    "      var s=o.getAttribute('aria-selected')==='true'||(' '+o.className+' ').indexOf(' selected ')>=0;\n"
    "      add(v,lab,s);\n"
    "    }\n"
    "  }\n"
    "  return out;\n"
    "}\n"
    "function capture(){\n"
    "  var t0=performance.now();\n"
    "  var vw=Math.round(document.documentElement.clientWidth||innerWidth||0);\n"
    "  var vh=Math.round(document.documentElement.clientHeight||innerHeight||0);\n"
    "  if(vw<1)vw=1;\n"
    "  if(vh<1)vh=1;\n"
    "  var boxes=[];\n"
    "  var view={x:0,y:0,w:vw,h:vh};\n"
    "  function pushTextNode(node,st,clip,op,z){\n"
    "    var raw=node.nodeValue; if(!raw)return;\n"
    "    var fg=mulA(argb(st.color),op);\n"
    "    var fs=px(st.fontSize); if(fs<=0)fs=14;\n"
    "    var fw=weightOf(st);\n"
    "    var ff=familyOf(st);\n"
    "    var range=document.createRange();\n"
    "    var n=raw.length;\n"
    "    if(n>8000) n=8000;\n"
    "    var run=null;\n"
    "    for(var i=0;i<n;i++){\n"
    "      range.setStart(node,i);\n"
    "      range.setEnd(node,i+1);\n"
    "      var r=range.getBoundingClientRect();\n"
    "      if(r.width<=0||r.height<=0) continue;\n"
    "      var ch=raw.charAt(i);\n"
    "      var bx={x:r.left,y:r.top,w:r.width,h:r.height};\n"
    "      if(!visClip(bx,clip,vw,vh)) continue;\n"
    "      if(run && Math.abs(r.top-run.y)<1 && Math.abs(r.left-(run.x+run.w))<1.6 && Math.abs(r.height-run.h)<1){\n"
    "        run.txt+=ch;\n"
    "        run.w=Math.round(r.left+r.width-run.x);\n"
    "      } else {\n"
    "        if(run) boxes.push(run);\n"
    "        run=makeBox(0,'#text',Math.round(r.left),Math.round(r.top),Math.round(r.width),Math.round(r.height),0,fg,fs,0,0,0,'','','','',ch,fw,ff,'',null,clip,z);\n"
    "      }\n"
    "    }\n"
    "    if(run) boxes.push(run);\n"
    "  }\n"
    "  function addPseudo(el,which,clip,op,z){\n"
    "    var st=getComputedStyle(el,which);\n"
    "    if(!st||st.display==='none'||st.visibility==='hidden')return;\n"
    "    var txt=cssContent(st.content);\n"
    "    var bg=mulA(argb(st.backgroundColor),op);\n"
    "    var g=mulA(gradientFill(st),op);\n"
    "    if(g&&!bg) bg=g;\n"
    "    var bw=px(st.borderTopWidth);\n"
    "    var ow=px(st.outlineWidth);\n"
    "    if(bw<=0&&ow>0&&st.outlineStyle&&st.outlineStyle!=='none'){bw=ow;}\n"
    "    var er=el.getBoundingClientRect();\n"
    "    var w=px(st.width), h=px(st.height);\n"
    "    if(w<=0) w=px(st.fontSize)||px(er.width);\n"
    "    if(h<=0) h=px(st.lineHeight)||px(st.fontSize)||px(er.height);\n"
    "    if(w<=0||h<=0){ if(!txt) return; w=w||px(st.fontSize)||12; h=h||px(st.fontSize)||12; }\n"
    "    var x=Math.round(er.left+px(st.left));\n"
    "    var y=Math.round(er.top+px(st.top));\n"
    "    if(st.position==='static'){ x=Math.round(er.left); y=Math.round(er.top); }\n"
    "    var box={x:x,y:y,w:Math.round(w),h:Math.round(h)};\n"
    "    if(!visClip(box,clip,vw,vh)) return;\n"
    "    var fg=mulA(argb(st.color),op);\n"
    "    var fs=px(st.fontSize); if(fs<=0)fs=14;\n"
    "    var sh=parseShadow(st.boxShadow);\n"
    "    sh.c=mulA(sh.c,op);\n"
    "    var b=makeBox(0,'#'+which.replace(':',''),box.x,box.y,box.w,box.h,bg,fg,fs,bw,mulA(argb(st.borderTopColor||st.outlineColor),op),rad(st,box.w,box.h),'','','','',txt,weightOf(st),familyOf(st),'',sh,clip,z);\n"
    "    boxes.push(b);\n"
    "  }\n"
    "  function walk(el,clip,opMul){\n"
    "    if(!el||el.nodeType!==1)return;\n"
    "    var tag=el.tagName.toLowerCase();\n"
    "    if(skipTag(tag))return;\n"
    "    var st=getComputedStyle(el);\n"
    "    if(!st||st.display==='none'||st.visibility==='hidden')return;\n"
    "    var op=opMul*(parseFloat(st.opacity)||1);\n"
    "    if(op<=0)return;\n"
    "    var r=el.getBoundingClientRect();\n"
    "    var x=Math.round(r.left),y=Math.round(r.top),w=Math.round(r.width),h=Math.round(r.height);\n"
    "    if(isBlockingOverlay(st,r,vw,vh)) return;\n"
    "    var kind=0;\n"
    "    if(tag==='input')kind=1;\n"
    "    else if(tag==='textarea')kind=2;\n"
    "    else if(tag==='a')kind=3;\n"
    "    else if(tag==='select')kind=6;\n"
    "    else if(tag==='button')kind=4;\n"
    "    else if(tag==='img'||tag==='svg'||tag==='canvas'||tag==='video'||tag==='iframe')kind=5;\n"
    "    else if(el.getAttribute('role')==='combobox')kind=6;\n"
    "    else if(el.getAttribute('role')==='button'||el.getAttribute('onclick'))kind=4;\n"
    "    else if(el.getAttribute('aria-haspopup')==='listbox'||el.getAttribute('aria-haspopup')==='true')kind=6;\n"
    "    else if(el.getAttribute('role')==='listbox'||el.getAttribute('role')==='option'||el.getAttribute('role')==='menuitem')kind=4;\n"
    "    var bg=mulA(argb(st.backgroundColor),op);\n"
    "    var g=mulA(gradientFill(st),op);\n"
    "    if(g&&!bg) bg=g;\n"
    "    var fg=mulA(argb(st.color),op);\n"
    "    var fs=px(st.fontSize); if(fs<=0)fs=14;\n"
    "    var bw=px(st.borderTopWidth);\n"
    "    var ow=px(st.outlineWidth);\n"
    "    if(bw<=0&&ow>0&&st.outlineStyle&&st.outlineStyle!=='none'){bw=ow;}\n"
    "    var bc=mulA(argb(st.borderTopColor||st.outlineColor),op);\n"
    "    var rr=rad(st,w,h);\n"
    "    var href=kind===3?String(el.getAttribute('href')||''):'';\n"
    "    var typ='';\n"
    "    if(kind===1||kind===2||kind===4||kind===6) typ=String(el.getAttribute('type')||el.type||'');\n"
    "    var id=String(el.id||el.getAttribute('name')||'');\n"
    "    var val='';\n"
    "    if(kind===1||kind===2||kind===6) val=String(el.value||'');\n"
    "    var txt='';\n"
    "    if(kind===1||kind===2){\n"
    "      if(val) txt=val;\n"
    "      else if(el.placeholder){ txt=String(el.placeholder); fg=mulA(argb('rgb(156,163,175)'),op); }\n"
    "    }\n"
    "    var sh=parseShadow(st.boxShadow);\n"
    "    sh.c=mulA(sh.c,op);\n"
    "    var z=parseInt(st.zIndex,10); if(!isFinite(z)) z=0;\n"
    "    var nextClip=clip;\n"
    "    if(st.overflow==='hidden'||st.overflow==='auto'||st.overflow==='scroll'||st.overflowX==='hidden'||st.overflowY==='hidden'){\n"
    "      nextClip=intersect(clip,{x:x,y:y,w:w,h:h});\n"
    "    }\n"
    "    var img=kind===5?imgData(el):'';\n"
    "    var harvested=[];\n"
    "    var cn=typeof el.className==='string'?el.className:'';\n"
    "    if(kind===6||tag==='select'||el.getAttribute('role')==='combobox'||el.getAttribute('aria-haspopup')||/\\b(ng-select|p-dropdown|select-container|combobox)\\b/i.test(cn)){\n"
    "      harvested=optionsOf(el);\n"
    "      if(harvested.length>0) kind=6;\n"
    "    }\n"
    "    var optsStr=encOpts(harvested);\n"
    "    var box={x:x,y:y,w:w,h:h};\n"
    "    var paint=visClip(box,clip,vw,vh)&&(bg!==0||kind>0||bw>0||sh.c!==0||img||optsStr||(st.backgroundImage&&st.backgroundImage!=='none'));\n"
    "    if(paint){\n"
    "      boxes.push(makeBox(kind,tag,x,y,w,h,bg,fg,fs,bw,bc,rr,href,typ,id,val,txt,weightOf(st),familyOf(st),img,sh,nextClip,z,optsStr));\n"
    "    }\n"
    "    addPseudo(el,'::before',nextClip,op,z);\n"
    "    var ch=el.childNodes;\n"
    "    for(var i=0;i<ch.length;i++){\n"
    "      var n=ch[i];\n"
    "      if(n.nodeType===3) pushTextNode(n,st,nextClip,op,z);\n"
    "      else if(n.nodeType===1) walk(n,nextClip,op);\n"
    "    }\n"
    "    addPseudo(el,'::after',nextClip,op,z);\n"
    "  }\n"
    "  walk(document.documentElement,view,1);\n"
    "  boxes.forEach(function(b,i){b.ord=i;});\n"
    "  boxes.sort(function(a,b){return (a.z-b.z)||(a.ord-b.ord);});\n"
    "  var ms=Math.round(performance.now()-t0);\n"
    "  var out='CLB3\\n'+vw+' '+vh+' '+boxes.length+' '+ms+'\\n';\n"
    "  for(var i=0;i<boxes.length;i++){\n"
    "    var b=boxes[i];\n"
    "    out+=[b.k,b.x,b.y,b.w,b.h,b.bg,b.fg,b.fs,b.bw,b.bc,b.rr,b.fw,b.sx,b.sy,b.sblur,b.sspread,b.sc,b.cx,b.cy,b.cw,b.ch].join(' ')+'\\n';\n"
    "    out+=esc(b.t)+'\\n'+esc(b.href)+'\\n'+esc(b.typ)+'\\n'+esc(b.id)+'\\n'+esc(b.val)+'\\n'+esc(b.txt)+'\\n'+esc(b.ff)+'\\n'+esc(b.img)+'\\n'+esc(b.opts||'')+'\\n';\n"
    "  }\n"
    "  return out;\n"
    "}\n"
    "function pageHasBlockingOverlay(){\n"
    "  var vw=Math.round(document.documentElement.clientWidth||innerWidth||0);\n"
    "  var vh=Math.round(document.documentElement.clientHeight||innerHeight||0);\n"
    "  var root=document.body||document.documentElement;\n"
    "  if(!root||!root.getElementsByTagName) return false;\n"
    "  var all=root.getElementsByTagName('*');\n"
    "  for(var i=0;i<all.length;i++){\n"
    "    var el=all[i];\n"
    "    var st=getComputedStyle(el);\n"
    "    if(!st||st.display==='none'||st.visibility==='hidden') continue;\n"
    "    if(parseFloat(st.opacity)===0) continue;\n"
    "    var r=el.getBoundingClientRect();\n"
    "    if(isBlockingOverlay(st,r,vw,vh)) return true;\n"
    "  }\n"
    "  return false;\n"
    "}\n"
    "function whenClear(){\n"
    "  return new Promise(function(resolve){\n"
    "    if(!pageHasBlockingOverlay()){ resolve(); return; }\n"
    "    var mo=new MutationObserver(function(){\n"
    "      if(!pageHasBlockingOverlay()){ mo.disconnect(); resolve(); }\n"
    "    });\n"
    "    mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class','style','hidden','aria-hidden','aria-busy']});\n"
    "  });\n"
    "}\n"
    "return whenClear().then(function(){ return capture(); });\n"
    "})();\n"
    "\n"
;
#endif
