#ifndef LIBP2P_BROWSER_LIVE_JS_H
#define LIBP2P_BROWSER_LIVE_JS_H
static const char kChengLibp2pBrowserLiveJS[] =
    "(function(){\n"
    "  if (window.__chengLive) return;\n"
    "  window.__chengLive = 1;\n"
    "  var pending = false;\n"
    "  function ask(){\n"
    "    if (pending) return;\n"
    "    pending = true;\n"
    "    requestAnimationFrame(function(){\n"
    "      requestAnimationFrame(function(){\n"
    "        pending = false;\n"
    "        try {\n"
    "          if (window.webkit && webkit.messageHandlers && webkit.messageHandlers.chengSnap) {\n"
    "            webkit.messageHandlers.chengSnap.postMessage('1');\n"
    "          } else if (window.chengHost && chengHost.snap) {\n"
    "            chengHost.snap();\n"
    "          }\n"
    "        } catch (e) {}\n"
    "      });\n"
    "    });\n"
    "  }\n"
    "  window.chengAskSnap = ask;\n"
    "  window.chengReplayPointer = function(x, y){\n"
    "    var el = document.elementFromPoint(x, y);\n"
    "    if (!el) { ask(); return; }\n"
    "    var opts = {bubbles:true, cancelable:true, composed:true, view:window, clientX:x, clientY:y, screenX:x, screenY:y, button:0, buttons:1, detail:1};\n"
    "    try {\n"
    "      if (window.PointerEvent) el.dispatchEvent(new PointerEvent('pointerdown', opts));\n"
    "    } catch (e1) {}\n"
    "    el.dispatchEvent(new MouseEvent('mousedown', opts));\n"
    "    if (el.focus) try { el.focus(); } catch (e2) {}\n"
    "    opts.buttons = 0;\n"
    "    try {\n"
    "      if (window.PointerEvent) el.dispatchEvent(new PointerEvent('pointerup', opts));\n"
    "    } catch (e3) {}\n"
    "    el.dispatchEvent(new MouseEvent('mouseup', opts));\n"
    "    el.dispatchEvent(new MouseEvent('click', opts));\n"
    "    ask();\n"
    "  };\n"
    "  window.chengReplayKey = function(code){\n"
    "    var el = document.activeElement || document.body;\n"
    "    var isBack = code === 8;\n"
    "    var key = isBack ? 'Backspace' : String.fromCharCode(code);\n"
    "    var init = {key:key, code:isBack ? 'Backspace' : key, keyCode:code, which:code, bubbles:true, cancelable:true, composed:true};\n"
    "    el.dispatchEvent(new KeyboardEvent('keydown', init));\n"
    "    var tag = el && el.tagName ? el.tagName : '';\n"
    "    if ((tag === 'INPUT' || tag === 'TEXTAREA') && !el.readOnly && !el.disabled) {\n"
    "      var proto = tag === 'TEXTAREA' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;\n"
    "      var desc = Object.getOwnPropertyDescriptor(proto, 'value');\n"
    "      var cur = el.value || '';\n"
    "      var next = cur;\n"
    "      if (isBack) next = cur.length ? cur.slice(0, -1) : cur;\n"
    "      else if (code >= 32 && code < 127) next = cur + String.fromCharCode(code);\n"
    "      if (desc && desc.set) desc.set.call(el, next);\n"
    "      else el.value = next;\n"
    "      el.dispatchEvent(new Event('input', {bubbles:true, composed:true}));\n"
    "    }\n"
    "    el.dispatchEvent(new KeyboardEvent('keyup', init));\n"
    "    if (code === 13) el.dispatchEvent(new Event('change', {bubbles:true, composed:true}));\n"
    "    ask();\n"
    "  };\n"
    "  document.addEventListener('click', ask, true);\n"
    "  document.addEventListener('input', ask, true);\n"
    "  document.addEventListener('change', ask, true);\n"
    "  var mo = new MutationObserver(ask);\n"
    "  var root = document.documentElement || document;\n"
    "  mo.observe(root, {subtree:true, childList:true, characterData:true, attributes:true, attributeFilter:['class','style','open','hidden','value','aria-expanded','aria-hidden']});\n"
    "})();\n"
    "\n"
;
#endif
