#ifndef LIBP2P_BROWSER_FP_JS_H
#define LIBP2P_BROWSER_FP_JS_H
static const char kChengLibp2pBrowserFpJS[] =
    "// 指纹 profile 注入(JS): 按 profile JSON 的确定性种子扰动读面 API。\n"
    "// 原则: 同一 profile 永远同指纹(可复现), 不同 profile 必不同; 所有覆写互洽。\n"
    "// 宿主把 profile 常量以 __chengFpProfile 注入(在本文档之前执行)。\n"
    "(function () {\n"
    "  \"use strict\";\n"
    "  if (window.__chengFp) return;\n"
    "  var P = window.__chengFpProfile || {};\n"
    "  function seedOf(str) {\n"
    "    var h = 2166136261;\n"
    "    for (var i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = (h * 16777619) >>> 0; }\n"
    "    return h >>> 0;\n"
    "  }\n"
    "  var BASE_SEED = seedOf(String(P.seed || \"cheng-fp-default\"));\n"
    "  function rng(tag) { // 每 tag 独立确定性流\n"
    "    var s = seedOf(tag + \":\" + BASE_SEED) || 1;\n"
    "    return function () { // mulberry32\n"
    "      s = (s + 0x6D2B79F5) >>> 0;\n"
    "      var t = s;\n"
    "      t = Math.imul(t ^ (t >>> 15), t | 1);\n"
    "      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);\n"
    "      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;\n"
    "    };\n"
    "  }\n"
    "  function def(obj, prop, val) {\n"
    "    try {\n"
    "      Object.defineProperty(obj, prop, { get: function () { return val; }, configurable: true });\n"
    "    } catch (e) {}\n"
    "  }\n"
    "\n"
    "  // ---- navigator 面 ----\n"
    "  if (P.userAgent) def(Navigator.prototype, \"userAgent\", P.userAgent);\n"
    "  if (P.platform) def(Navigator.prototype, \"platform\", P.platform);\n"
    "  if (P.languages) def(navigator, \"languages\", Object.freeze(P.languages.slice()));\n"
    "  if (P.languages && P.languages.length) def(navigator, \"language\", P.languages[0]);\n"
    "  if (P.hardwareConcurrency) def(navigator, \"hardwareConcurrency\", P.hardwareConcurrency);\n"
    "  if (P.deviceMemory) def(navigator, \"deviceMemory\", P.deviceMemory);\n"
    "  if (P.maxTouchPoints !== undefined) def(navigator, \"maxTouchPoints\", P.maxTouchPoints);\n"
    "\n"
    "  // ---- 时区面: Date + Intl 同步 ----\n"
    "  if (typeof P.tzOffsetMinutes === \"number\") {\n"
    "    var off = P.tzOffsetMinutes;\n"
    "    Date.prototype.getTimezoneOffset = function () { return off; };\n"
    "    try {\n"
    "      var DF = Intl.DateTimeFormat;\n"
    "      var realResolved = DF.prototype.resolvedOptions;\n"
    "      DF.prototype.resolvedOptions = function () {\n"
    "        var o = realResolved.call(this);\n"
    "        if (P.tzIana) o.timeZone = P.tzIana;\n"
    "        if (P.locale) o.locale = P.locale;\n"
    "        return o;\n"
    "      };\n"
    "    } catch (e) {}\n"
    "  }\n"
    "  if (P.locale) def(navigator, \"language\", P.locale);\n"
    "\n"
    "  // ---- ClientRects 面: 确定性亚像素抖动(字体枚举/指纹探测的部分缓解) ----\n"
    "  // 捕获脚本读矩形时置 window.__chengCaptureActive=1 → 旁路噪声(1:1 不受影响)。\n"
    "  if (P.rectsNoise !== 0) {\n"
    "    function jitterRect(r, el) {\n"
    "      if (window.__chengCaptureActive) return r;\n"
    "      try {\n"
    "        var key = (el && el.id ? el.id : \"\") + \"|\" + (el && el.className ? String(el.className).slice(0, 24) : \"\") + \"|\" + Math.round(r.width * 10);\n"
    "        var rand = rng(\"rects:\" + key);\n"
    "        var j = function () { return (rand() - 0.5) * 0.5; }; // ±0.25px\n"
    "        return new DOMRect(r.x + j(), r.y + j(), r.width + j(), r.height + j());\n"
    "      } catch (e) { return r; }\n"
    "    }\n"
    "    var origGBCR = Element.prototype.getBoundingClientRect;\n"
    "    Element.prototype.getBoundingClientRect = function () {\n"
    "      var r = origGBCR.call(this);\n"
    "      return jitterRect(r, this);\n"
    "    };\n"
    "    var origGCRs = Element.prototype.getClientRects;\n"
    "    Element.prototype.getClientRects = function () {\n"
    "      var list = origGCRs.call(this);\n"
    "      try {\n"
    "        if (list && list.length) {\n"
    "          var j = jitterRect(list[0], this);\n"
    "          if (j !== list[0]) {\n"
    "            var out = [];\n"
    "            for (var i = 0; i < list.length; i++) out.push(list[i]);\n"
    "            out[0] = j;\n"
    "            return out;\n"
    "          }\n"
    "        }\n"
    "      } catch (e) {}\n"
    "      return list;\n"
    "    };\n"
    "  }\n"
    "\n"
    "  // ---- canvas 面: 读出时按种子注入确定性低位噪声 ----\n"
    "  function noiseCanvas(canvas, ctx2d) {\n"
    "    try {\n"
    "      var w = canvas.width, h = canvas.height;\n"
    "      if (w <= 0 || h <= 0 || w * h > 4000000) return;\n"
    "      var img = ctx2d.getImageData(0, 0, w, h);\n"
    "      var d = img.data;\n"
    "      var rand = rng(\"canvas:\" + w + \"x\" + h);\n"
    "      var stride = 97; // 每 stride 像素扰动一个通道 ±1: 足够改变哈希, 肉眼不可见\n"
    "      for (var i = 0; i < d.length; i += 4 * stride) {\n"
    "        var delta = rand() < 0.5 ? -1 : 1;\n"
    "        var ch = i + 4 * Math.floor(rand() * 3);\n"
    "        if (ch < d.length) d[ch] = Math.max(0, Math.min(255, d[ch] + delta));\n"
    "      }\n"
    "      ctx2d.putImageData(img, 0, 0);\n"
    "    } catch (e) {}\n"
    "  }\n"
    "  function wrapRead(ctx) {\n"
    "    var origGet = ctx.getImageData;\n"
    "    ctx.getImageData = function (sx, sy, sw, sh) {\n"
    "      var img = origGet.call(this, sx, sy, sw, sh);\n"
    "      try {\n"
    "        var d = img.data;\n"
    "        var rand = rng(\"gid:\" + sw + \"x\" + sh + \":\" + sx + \",\" + sy);\n"
    "        var stride = 97;\n"
    "        for (var i = 0; i < d.length; i += 4 * stride) {\n"
    "          var delta = rand() < 0.5 ? -1 : 1;\n"
    "          var ch = i + 4 * Math.floor(rand() * 3);\n"
    "          if (ch < d.length) d[ch] = Math.max(0, Math.min(255, d[ch] + delta));\n"
    "        }\n"
    "      } catch (e) {}\n"
    "      return img;\n"
    "    };\n"
    "    return ctx;\n"
    "  }\n"
    "  var origGetContext = HTMLCanvasElement.prototype.getContext;\n"
    "  HTMLCanvasElement.prototype.getContext = function (type) {\n"
    "    var ctx = origGetContext.apply(this, arguments);\n"
    "    if (ctx && type === \"2d\" && !ctx.__chengFpWrapped) {\n"
    "      try {\n"
    "        wrapRead(ctx);\n"
    "        var origDataUrl = HTMLCanvasElement.prototype.toDataURL;\n"
    "        if (!origDataUrl.__chengFpPatched) {\n"
    "          HTMLCanvasElement.prototype.toDataURL = function () {\n"
    "            try { noiseCanvas(this, this.getContext(\"2d\")); } catch (e) {}\n"
    "            return origDataUrl.apply(this, arguments);\n"
    "          };\n"
    "          origDataUrl.__chengFpPatched = true;\n"
    "        }\n"
    "        ctx.__chengFpWrapped = true;\n"
    "      } catch (e) {}\n"
    "    }\n"
    "    return ctx;\n"
    "  };\n"
    "\n"
    "  // ---- WebGL 面: 厂商/渲染器覆写 + readPixels 噪声 ----\n"
    "  if (P.webglVendor || P.webglRenderer) {\n"
    "    var origWgl = HTMLCanvasElement.prototype.getContext; // 已被上方包裹, 取原链\n"
    "  }\n"
    "  // getParameter 覆写放在原型上(2d/webgl 共用入口已被包裹, 这里另挂 gl 原型)\n"
    "  function patchGLProto(proto) {\n"
    "    if (!proto || proto.__chengFpGL) return;\n"
    "    proto.__chengFpGL = true;\n"
    "    var origParam = proto.getParameter;\n"
    "    proto.getParameter = function (p) {\n"
    "      if (P.webglVendor && (p === 37445 /* UNMASKED_VENDOR_WEBGL */ || p === 7936 /* VENDOR */)) {\n"
    "        return P.webglVendor;\n"
    "      }\n"
    "      if (P.webglRenderer && (p === 37446 /* UNMASKED_RENDERER_WEBGL */ || p === 7937 /* RENDERER */)) {\n"
    "        return P.webglRenderer;\n"
    "      }\n"
    "      return origParam.call(this, p);\n"
    "    };\n"
    "    var origRead = proto.readPixels;\n"
    "    proto.readPixels = function (x, y, w, h, fmt, type, pixels) {\n"
    "      origRead.call(this, x, y, w, h, fmt, type, pixels);\n"
    "      try {\n"
    "        if (!pixels || !pixels.length) return;\n"
    "        var rand = rng(\"glread:\" + w + \"x\" + h + \":\" + x + \",\" + y);\n"
    "        var stride = 61;\n"
    "        for (var i = 0; i < pixels.length; i += 4 * stride) {\n"
    "          var delta = rand() < 0.5 ? -1 : 1;\n"
    "          var ch = i + Math.floor(rand() * 4);\n"
    "          pixels[ch] = Math.max(0, Math.min(255, pixels[ch] + delta));\n"
    "        }\n"
    "      } catch (e) {}\n"
    "    };\n"
    "  }\n"
    "  if (window.WebGLRenderingContext) patchGLProto(WebGLRenderingContext.prototype);\n"
    "  if (window.WebGL2RenderingContext) patchGLProto(WebGL2RenderingContext.prototype);\n"
    "\n"
    "  // ---- AudioContext 面: 确定性噪声 ----\n"
    "  if (window.AnalyserNode && P.audioSeed !== 0) {\n"
    "    var origGetFloat = AnalyserNode.prototype.getFloatFrequencyData;\n"
    "    AnalyserNode.prototype.getFloatFrequencyData = function (arr) {\n"
    "      origGetFloat.call(this, arr);\n"
    "      var rand = rng(\"audio:\" + arr.length);\n"
    "      for (var i = 0; i < arr.length; i += 7) arr[i] += (rand() - 0.5) * 0.01;\n"
    "    };\n"
    "    var origGetByte = AnalyserNode.prototype.getByteFrequencyData;\n"
    "    AnalyserNode.prototype.getByteFrequencyData = function (arr) {\n"
    "      origGetByte.call(this, arr);\n"
    "      var rand = rng(\"audiob:\" + arr.length);\n"
    "      for (var i = 0; i < arr.length; i += 11) arr[i] = Math.max(0, Math.min(255, arr[i] + (rand() < 0.5 ? -1 : 1)));\n"
    "    };\n"
    "  }\n"
    "\n"
    "  // ---- WebRTC 面: 剥真实 ICE 候选(防本机/内网 IP 泄露) ----\n"
    "  if (P.webrtcMode === \"disable\" && window.RTCPeerConnection) {\n"
    "    window.RTCPeerConnection = function () {\n"
    "      throw new Error(\"WebRTC disabled by profile\");\n"
    "    };\n"
    "    window.RTCPeerConnection.prototype = RTCPeerConnection.prototype;\n"
    "  }\n"
    "\n"
    "})();\n"
    "\n"
    ;
#endif