#!/usr/bin/python3
import ctypes
import errno
import os
import platform
import stat
import sys


def fail(reason: str) -> None:
    raise SystemExit("ts_csg_atomic_publish:" + reason)


def require_real_directory(path: str, label: str) -> os.stat_result:
    try:
        info = os.lstat(path)
    except FileNotFoundError:
        fail(label + "_missing")
    if not stat.S_ISDIR(info.st_mode) or stat.S_ISLNK(info.st_mode):
        fail(label + "_not_real_directory")
    return info


def same_identity(left: os.stat_result, right: os.stat_result) -> bool:
    return (
        left.st_dev == right.st_dev
        and left.st_ino == right.st_ino
        and left.st_mode == right.st_mode
        and left.st_nlink == right.st_nlink
    )


def main() -> None:
    if len(sys.argv) != 4 or sys.argv[1] not in ("exchange", "noreplace"):
        fail("arguments_invalid")
    mode = sys.argv[1]
    source = os.path.abspath(sys.argv[2])
    destination = os.path.abspath(sys.argv[3])
    source_parent = os.path.dirname(source)
    destination_parent = os.path.dirname(destination)
    if source_parent != destination_parent or source == destination:
        fail("same_parent_distinct_paths_required")
    if os.path.realpath(source_parent) != source_parent:
        fail("parent_path_not_canonical")
    parent_info = require_real_directory(source_parent, "parent")
    source_info = require_real_directory(source, "source")
    destination_exists = os.path.lexists(destination)
    if mode == "exchange":
        if not destination_exists:
            fail("exchange_destination_missing")
        destination_info = require_real_directory(destination, "destination")
    elif destination_exists:
        fail("noreplace_destination_exists")

    directory_flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0)
    if hasattr(os, "O_CLOEXEC"):
        directory_flags |= os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        directory_flags |= os.O_NOFOLLOW
    parent_fd = os.open(source_parent, directory_flags)
    try:
        if not same_identity(parent_info, os.fstat(parent_fd)):
            fail("parent_identity_drifted")
        bound_source = os.stat(
            os.path.basename(source), dir_fd=parent_fd, follow_symlinks=False
        )
        if not same_identity(source_info, bound_source):
            fail("source_identity_drifted")
        if mode == "exchange":
            bound_destination = os.stat(
                os.path.basename(destination),
                dir_fd=parent_fd,
                follow_symlinks=False,
            )
            if not same_identity(destination_info, bound_destination):
                fail("destination_identity_drifted")
        libc = ctypes.CDLL(None, use_errno=True)
        system = platform.system()
        if system == "Darwin":
            operation = getattr(libc, "renameatx_np", None)
            flag = 0x00000002 if mode == "exchange" else 0x00000004
        elif system == "Linux":
            operation = getattr(libc, "renameat2", None)
            flag = 0x00000002 if mode == "exchange" else 0x00000001
        else:
            fail("platform_unsupported")
        if operation is None:
            fail("atomic_rename_unavailable")
        operation.argtypes = (
            ctypes.c_int,
            ctypes.c_char_p,
            ctypes.c_int,
            ctypes.c_char_p,
            ctypes.c_uint,
        )
        operation.restype = ctypes.c_int
        result = operation(
            parent_fd,
            os.fsencode(os.path.basename(source)),
            parent_fd,
            os.fsencode(os.path.basename(destination)),
            flag,
        )
        if result != 0:
            error_number = ctypes.get_errno()
            if error_number in (errno.EEXIST, errno.ENOTEMPTY):
                fail("destination_raced")
            if error_number == errno.EXDEV:
                fail("cross_device_rename_rejected")
            fail("atomic_rename_failed:" + str(error_number))
        try:
            os.fsync(parent_fd)
        except OSError as error:
            fail("parent_fsync_failed:" + str(error.errno))
    finally:
        os.close(parent_fd)


if __name__ == "__main__":
    main()
