export type CsgFact = {
    [key: string]: unknown;
};
export type TranspileDiagnostic = {
    functionId: string;
    functionName: string;
    opId: string;
    reason: string;
};
export type TranspileFunctionResult = {
    ok: boolean;
    name: string;
    code: string;
    preludeUsed: Set<string>;
    structsUsed: Set<string>;
    diagnostics: TranspileDiagnostic[];
};
type OpFact = CsgFact & {
    id: string;
    opKind: string;
    block?: string;
    ordinal?: number;
};
type TypeDeclMember = {
    name: string;
    optional: boolean;
    type: string;
};
export type HandleTeardownBridge = {
    bridgeFn: string;
    eventProps: readonly string[];
    closeMethod: string;
};
export declare class TranspilerFactIndex {
    readonly opsById: Map<string, OpFact>;
    private opsByFnCache;
    opsOf(fid: string): OpFact[];
    readonly opsByBlock: Map<string, OpFact[]>;
    readonly functionById: Map<string, CsgFact>;
    readonly functionByName: Map<string, CsgFact>;
    readonly functionByNameInFile: Map<string, CsgFact>;
    readonly dataById: Map<string, unknown>;
    readonly typeDeclByName: Map<string, CsgFact>;
    readonly typeDeclsByFile: Map<string, CsgFact[]>;
    readonly typeImportsByFile: Map<string, Map<string, string>>;
    private typeDeclsBySpecCache;
    typeDeclByModuleSpec(spec: string): CsgFact[] | undefined;
    readonly qualifiedTypeOrigin: Map<string, string>;
    readonly constLiterals: Map<string, string>;
    readonly constObjectMembers: Map<string, Map<string, string>>;
    readonly constLiteralTypes: Map<string, string>;
    readonly catchParamsByFunction: Map<string, Set<string>>;
    readonly jsxById: Map<string, CsgFact>;
    readonly jsxFactByOpId: Map<string, CsgFact>;
    readonly childOpReferenced: Set<string>;
    readonly iconNames: Set<string>;
    readonly constArrayElemTypes: Map<string, string>;
    readonly const2dRowElemTypes: Map<string, string>;
    readonly const2dRowStructNames: Set<string>;
    readonly moduleVarSymbols: Map<string, CsgFact[]>;
    const2dRowStructOf(name: string): {
        struct: string;
        elemText: string;
    } | undefined;
    ensure2dRowDecl(rowStruct: string, elemText: string): void;
    registerFileLevelArrowFunctions(facts: readonly CsgFact[]): void;
    constructor(facts: readonly CsgFact[], functionAliases?: ReadonlyMap<string, string>, baseIndex?: TranspilerFactIndex);
    readonly aliasNames: Set<string>;
    private applyFunctionAliases;
}
export declare class TypeMapper {
    readonly usedStructs: Set<string>;
    private readonly index;
    readonly unionFlattenShapeTargets: Map<string, string>;
    constructor(index: TranspilerFactIndex);
    private flattenStructUnionPartMembers;
    private tryFlattenStructUnion;
    private inlineTwinMemo;
    inlineObjectStructuralTwin(t: string, members: TypeDeclMember[]): string | undefined;
    map(typeSource: string): {
        type?: string;
        reason?: string;
    };
    private isRecursiveJsonAliasDomain;
    zeroValueOf(chengType: string): string;
    emitStructs(): {
        code: string;
        diagnostics: string[];
    };
}
export declare function stripImportPrefixes(t: string): string;
export declare const DEFAULT_R2C_HOST_BRIDGES: Map<string, string>;
export declare const PRELUDE_SOURCES: Map<string, string>;
export declare class ChengFunctionTranspiler {
    private readonly index;
    private readonly types;
    private readonly diagnostics;
    readonly archivedNotes: TranspileDiagnostic[];
    private readonly fnValueTableLocals;
    fnArchiveBoundary: boolean;
    private readonly hostDomLocals;
    private readonly hostDomConsumedOnlyLocals;
    private hostDomConsumedComputed;
    private readonly archivedListenerCallbackLocals;
    private listenerLocalsComputed;
    readonly preludeUsed: Set<string>;
    private fnId;
    private fnName;
    private readonly localTypes;
    private readonly constBindings;
    private tmpCounter;
    readonly monomorphRequests: Array<{
        name: string;
        mangled: string;
        overrides: Map<number, string>;
    }>;
    readonly propNavigatePagesUsed: Set<string>;
    private readonly awaitTempByOpId;
    localAliasTargets: Map<string, string>;
    localAliasEmitNames: Map<string, string>;
    localAliasCaptures: Map<string, string[]>;
    setLocalAliasTargets(m: ReadonlyMap<string, string>): void;
    usedFvSubsetOf(targetFnId: string, candidates: string[]): string[];
    readonly jsonStructEncoderRequests: Set<string>;
    private jsonStructEncoderName;
    private jsonArrayEncoderName;
    readonly deepCloneRequests: Set<string>;
    readonly jsonDecodeRequests: Set<string>;
    private deepCloneStructHelperName;
    private deepCloneArrayHelperName;
    readonly auxiliaryFunctions: string[];
    deferredFrameKind: number | undefined;
    deferredResumeCallbackFid: string | undefined;
    deferredMs: number;
    recvDoneFrameKind: number | undefined;
    recvDoneResumeCallbackFid: string | undefined;
    moduleLetSlots?: ReadonlyMap<string, {
        slotVar: string;
        chengType: string;
        tsType: string;
    }>;
    moduleLetUsedKeys?: Set<string>;
    private fnFile;
    private readonly stateShellLocals;
    readonly monoTypeParamSubs: Map<string, string>;
    private readonly paramLocals;
    private readonly promiseAllElemTemps;
    private readonly typedZeroArrayDeclByOpId;
    private readonly externNames;
    private readonly stateSetterNames;
    private readonly hostBridges;
    private readonly hostObjects;
    private readonly boxRefSlots;
    private readonly objBoxRefSlots;
    private readonly setBoxRefSlots;
    private readonly arrBoxRefSlots;
    private readonly structBoxRefSlots;
    private readonly recvDoneSendBridges;
    private readonly handleTeardownBridges;
    setterTypes: ReadonlyMap<string, string>;
    private readonly propCallbacks;
    private readonly refStateMirrors;
    private handleAliasSource;
    private functionHasOtherWriteToName;
    constructor(index: TranspilerFactIndex, types: TypeMapper, externNames?: ReadonlySet<string>, stateSetterNames?: ReadonlySet<string>, hostBridges?: ReadonlyMap<string, string>, hostObjects?: ReadonlySet<string>, boxRefSlots?: ReadonlyMap<string, string>, objBoxRefSlots?: ReadonlyMap<string, ReadonlyMap<string, string>>, setBoxRefSlots?: ReadonlyMap<string, string>, recvDoneSendBridges?: ReadonlyMap<string, string>, arrBoxRefSlots?: ReadonlyMap<string, string>, structBoxRefSlots?: ReadonlyMap<string, string>, handleTeardownBridges?: ReadonlyMap<string, HandleTeardownBridge>, refStateMirrors?: ReadonlySet<string>, propCallbacks?: ReadonlyMap<string, string>, setterTypes?: ReadonlyMap<string, string>);
    narrowAnyReturnToVoid: boolean;
    inlineLambdaMode: boolean;
    dropEntryParams: boolean;
    setterEmitNames: ReadonlyMap<string, string>;
    setterStateNames: ReadonlyMap<string, string>;
    boxRefGlobalNames: ReadonlyMap<string, string>;
    preferredEventParamType: string | undefined;
    propCalleeAliases: ReadonlyMap<string, string>;
    compiledCalleeFvLists?: ReadonlyMap<string, readonly string[]>;
    private readonly emittedExprVars;
    globalStateSlots?: ReadonlyMap<string, {
        slotVar: string;
        chengType: string;
    }>;
    globalRefSlots?: ReadonlyMap<string, {
        slotVar: string;
        chengType: string;
    }>;
    fnRefAliases?: ReadonlyMap<string, {
        ref: string;
        alias: string;
    }>;
    fnValueLocals?: Map<string, string>;
    fnValueBridgesEmitted?: Set<string>;
    readonly inlineLambdas: string[];
    readonly extraPreludeFns: string[];
    extraPreludeFnsPush: (txt: string) => void;
    captureRenames?: ReadonlyMap<string, {
        expr: string;
        type?: string;
        writable?: boolean;
    }>;
    hookMemberBridges?: ReadonlyMap<string, string>;
    hookFnAliases?: ReadonlyMap<string, string>;
    hookMemberShells?: ReadonlyMap<string, string>;
    refusedRefReasons?: ReadonlyMap<string, string>;
    hookResultLocals?: ReadonlyMap<string, ReadonlyMap<string, {
        kind: "capture";
        expr: string;
        type?: string;
    } | {
        kind: "call";
        emitName: string;
    }>>;
    paramRenames: Map<string, string>;
    fnValueOpIdByLocal: Map<string, string>;
    declaredReturnOverride: string | undefined;
    touchAliases: Map<string, string>;
    propsCallbacks?: ReadonlyMap<string, string>;
    private chengScalarToTsType;
    private objectLiteralShape;
    private synthStructName;
    private synthesizeObjectStruct;
    private unionFlattenShapeTarget;
    private r2cEntryTupleShape;
    private tuplePairEntryShape;
    private recordTextEntryTags;
    protected recordDictIdentityOf(argOpId: string): {
        mapT: string;
        entryT: string;
        kt: string;
        vt: string;
    } | undefined;
    private exprEntriesChainRecvType;
    private exprEntriesMapElemType;
    protected exprEntriesChainTypeOf(op: OpFact): string | undefined;
    private objBoxRefPresentVar;
    private objBoxRefFieldVar;
    private objBoxRefCurrentName;
    private objBoxRefFieldAccess;
    private boxRefCurrentName;
    private boxRefSlotVar;
    private switchBodyStructType;
    private inferBareSetElemType;
    private nestedConstMemberLiteral;
    private structPresenceFieldOf;
    private bareFnFactOf;
    private fileconstObjectMemberCache;
    private fileconstObjectMember;
    private fnUsesLocalAsJsxTag;
    private fileconstObjectAllMembers;
    private setBoxRefCurrentName;
    private arrBoxRefCurrentName;
    private structBoxRefCurrentName;
    private structBoxRefPresentExpr;
    private refStateMirrorCurrentName;
    private resolveStatementBlockOps;
    private tryFoldHandleTeardown;
    private matchSetTimeoutDeferred;
    private matchAsyncIifeAwait;
    private lowerAsyncIifeAwaitSplit;
    emitDeferredResumeBody(callbackFid: string): string[] | undefined;
    emitAsyncResumeBody(innerFid: string): string[] | undefined;
    private hostObjectCurrentRead;
    private hostVideoRefCurrentName;
    private typeDeclFieldOf;
    private indexSignatureCarrierReadType;
    private optionalAbsentFieldType;
    private zeroValueExprFor;
    private fnReturnsBareGlobalSlot;
    private isUndefinedishOperand;
    private hostVideoHandleExpr;
    private hostFullscreenElementRead;
    private injectedFvNames;
    private tryMarkStack;
    private catchParamStack;
    private currentReturnType;
    private errorValueIdentOf;
    private constantConditionOf;
    private returnTypeWithOverrides;
    private returnTypeNarrowedForInstance;
    transpileWithInjectedParams(functionId: string, emitName: string, freeVarTypes: ReadonlyMap<string, string>, paramTypes?: ReadonlyMap<string, string>, paramOverrides?: ReadonlyMap<number, string>): TranspileFunctionResult;
    transpile(functionId: string, emitNameOverride?: string, paramOverrides?: ReadonlyMap<number, string>): TranspileFunctionResult;
    private stubReturnLines;
    private stubDerivedTypeParamFallback;
    private objectLiteralIsAllFnValues;
    private diagnosticsRideAuditedArchiveChannels;
    private result;
    private fail;
    private archived;
    private freshVar;
    private entryBlockOf;
    private emitBlock;
    private emitBlockInner;
    private emitLogicalStatement;
    private emitHostDomDownloadArchive;
    private isSetterOnlyBlockCatchContinuation;
    private emitHostFileInputArchive;
    private emitStatementOperand;
    private emitCondition;
    private voidZeroReturnStmt;
    private inferLocalType;
    private mapReturnTypeText;
    private readonly walkBodyReturnChainVisiting;
    private walkBodyReturnChainType;
    private walkBodyReturnChainTypeInner;
    private spreadStructLiteralType;
    private readShapeEquals;
    private isArrayGuardArg;
    private guardedJsonArrayTernaryType;
    private ternaryScalarStrCarrier;
    private guardedTypeofJsonTernary;
    private isArrayGuardedJsonArrayCall;
    private blockSubtreeContains;
    private typeofStringGuardedJsonCall;
    private arrayLiteralOfBoolAndStr;
    private isSingleLayerJsonParseCast;
    private exprType;
    emitHookDerivedExpr(opId: string, ownerFnId?: string): {
        text: string | undefined;
        type: string | undefined;
        reason?: string;
    };
    emitHookDerivedFn(opId: string, ownerFnId: string, emitName: string): {
        code: string | undefined;
        chengType: string | undefined;
        reason?: string;
    };
    private emitExpr;
    private emitExprInner;
    private resolveArrowReturnExpr;
    private resolveZeroArgLocalReturnExpr;
    private emitArrowBindings;
    private exprTypeUnderRenames;
    private inlineArrowExpr;
    private renameStack;
    private pendingNullZeroType;
    private readonly emittedStructTempType;
    private pendingFieldStructType;
    private contextualTargetType;
    private declaredMemberType;
    private isDirectLiteral;
    private isNullishAtomOp;
    private literalConstructsAsCtxReturn;
    private localWriteCountInFn;
    private emitExprWithRenames;
    private emitNameOf;
    private moduleLetOf;
    private isSideEffectFreeSubtree;
    private thisKeywordRootedReceiver;
    private receiverIdentifierWitness;
    private renameOf;
    private emitCall;
    private sharedStrArgs;
    private declMembersWithSupers;
    private formalStructCopyPlan;
    private emitFormalStructCopy;
    private materializeAsFormalStruct;
    private adaptStructStore;
    private inferBodyReturnType;
    private bodyReturnsAllVoidish;
    private bodyReturnsAreVoidSetterCalls;
    private buildCaptureRenames;
    private compileInlineLambda;
    private emitJsxContainer;
    private emitJsxFactSubtree;
    private resolveJsxChildOpsBySpan;
    private emitJsxStrFromPropList;
    private emitJsxExpressionText;
    private listRenderPairDestructure;
    private pushListPairBindings;
    private listRenderArrayIndexDestructure;
    private popListPairBindings;
    private emitJsxChildElementSubtree;
    private jsxCountedFromArrowShape;
    private emitJsxCountedFromLoop;
    private emitListLoopRecvExpr;
    private emitJsxListRenderSubtree;
    private countedListReceiverLenOp;
    private iifeTargetFnId;
    private jsxReturnNullish;
    private jsxReturnMountFact;
    private planJsxIifeSubtree;
    private emitJsxIifeSubtree;
    private emitJsxListBlockLinearized;
    private ternBranchShapeOk;
    private ternListArmShapeOk;
    private emitTernBranch;
    private emitTernaryJsxTree;
    private emitJsxStrArg;
    private arrayCallbackTargetFid;
    private compileBlockArrowHelper;
    private tryEmitRecordDict;
    private pureCloneRead;
    private cloneShapedValue;
    private cloneShapedConstructorT;
    private canDeepCloneType;
    private deepCloneCloneExpr;
    deepCloneHelperText(t: string): string[];
    jsonStructEncoderHelperText(t: string): string[];
    private tryEmitJsonRoundtripDeepClone;
    private canJsonEncodeType;
    private canJsonDecodeType;
    private jsonDecodeStructHelperName;
    private jsonDecodeArrayHelperName;
    private jsonDecodeMemberExpr;
    jsonDecodeHelperText(t: string): string[];
    private tryEmitJsonParseDecode;
    private isAnnotatedJsonArrayNodeReceiver;
    private tryEmitJsonNodeMapDecode;
    private emitArrayMethod;
    private arrayCallbackParamMaps;
    private inlineArrowCondition;
    private exprTypeWithBinding;
}
export declare function mapParamType(facts: readonly CsgFact[], typeSource: string, baseIndex?: TranspilerFactIndex): string | undefined;
export declare function transpileClosure(facts: readonly CsgFact[], closureFunctionId: string, emitName: string, freeVarTypes: ReadonlyMap<string, string>, externImpls?: ReadonlyMap<string, string>, stateSetterNames?: ReadonlySet<string>, paramTypes?: ReadonlyMap<string, string>, hostBridges?: ReadonlyMap<string, string>, hostObjects?: ReadonlySet<string>, boxRefSlots?: ReadonlyMap<string, string>, objBoxRefSlots?: ReadonlyMap<string, ReadonlyMap<string, string>>, setBoxRefSlots?: ReadonlyMap<string, string>, deferredFrameKind?: number, recvDoneFrameKind?: number, recvDoneSendBridges?: ReadonlyMap<string, string>, localFunctionAliases?: ReadonlyMap<string, string>, baseIndex?: TranspilerFactIndex, arrBoxRefSlots?: ReadonlyMap<string, string>, structBoxRefSlots?: ReadonlyMap<string, string>, handleTeardownBridges?: ReadonlyMap<string, HandleTeardownBridge>, refStateMirrors?: ReadonlySet<string>, propCallbacks?: ReadonlyMap<string, string>, setterTypes?: ReadonlyMap<string, string>, narrowAnyReturnToVoid?: boolean, setterEmitNames?: ReadonlyMap<string, string>, setterStateNames?: ReadonlyMap<string, string>, boxRefGlobalNames?: ReadonlyMap<string, string>, propCalleeAliases?: ReadonlyMap<string, string>, compiledCalleeFvLists?: ReadonlyMap<string, readonly string[]>): {
    code: string;
    results: TranspileFunctionResult[];
    structDiagnostics: string[];
    deferred?: {
        kind: number;
        resumeFnName: string;
        ms: number;
    };
    recvDone?: {
        kind: number;
        resumeFnName: string;
    };
    jsonStructEncoders: string[];
};
export type StateSlot = {
    stateName: string;
    setterName: string;
    chengType: string;
    slotVar: string;
    initialExpr: string;
    setterEmitName?: string;
    presenceField?: string;
    presenceInitTruthy?: boolean;
};
export type EmitStateSlotsOptions = {
    slotNamePrefix?: string;
    setterEmitPrefix?: string;
    dirtyVar?: string;
    noWrappers?: boolean;
    additionalInitLines?: readonly string[];
    hookMemberBridges?: ReadonlyMap<string, {
        bridge: string;
        ret: string;
    }>;
};
export declare function emitStateSlots(facts: readonly CsgFact[], componentFunctionId: string, prefix: string, wanted: readonly string[], baseIndex?: TranspilerFactIndex, options?: EmitStateSlotsOptions): {
    code: string;
    slots: StateSlot[];
    diagnostics: string[];
    initLines: string[];
};
export type TranspileR2cOptions = {
    globalStateSlots?: ReadonlyMap<string, {
        slotVar: string;
        chengType: string;
    }>;
    globalRefSlots?: ReadonlyMap<string, {
        slotVar: string;
        chengType: string;
    }>;
    fnRefAliases?: ReadonlyMap<string, {
        ref: string;
        alias: string;
    }>;
    fnValueLocals?: Map<string, string>;
    fnValueBridgesEmitted?: Set<string>;
    stateSetterNames?: ReadonlySet<string>;
    setterTypes?: ReadonlyMap<string, string>;
    hostBridges?: ReadonlyMap<string, string>;
    r2cPreludeCode?: string;
    narrowAnyReturnToVoid?: boolean;
    alwaysPrelude?: readonly string[];
    zeroArityEntryName?: string;
    r2cSlotTypes?: readonly string[];
    componentCaptures?: ReadonlyMap<string, string | {
        expr: string;
        type?: string;
    }>;
    propsCallbacks?: ReadonlyMap<string, string>;
    forceStructs?: readonly string[];
    hookMemberBridges?: ReadonlyMap<string, string>;
    setterEmitNames?: ReadonlyMap<string, string>;
    hookFnAliases?: ReadonlyMap<string, string>;
    hookMemberShells?: ReadonlyMap<string, string>;
    refusedRefReasons?: ReadonlyMap<string, string>;
    hookResultLocals?: ReadonlyMap<string, ReadonlyMap<string, {
        kind: "capture";
        expr: string;
        type?: string;
    } | {
        kind: "call";
        emitName: string;
    }>>;
    hookArrowItems?: readonly {
        fnId: string;
        emitName: string;
        stateSlots?: ReadonlyMap<string, {
            slotVar: string;
            chengType: string;
        }>;
        refSlots?: ReadonlyMap<string, {
            slotVar: string;
            chengType: string;
        }>;
        stateSetterNames?: ReadonlySet<string>;
        setterTypes?: ReadonlyMap<string, string>;
        setterEmitNames?: ReadonlyMap<string, string>;
        captures?: ReadonlyMap<string, {
            expr: string;
            type?: string;
        }>;
        localAliasTargets?: ReadonlyMap<string, string>;
        localAliasEmitNames?: ReadonlyMap<string, string>;
        archiveBoundary?: boolean;
    }[];
    extraTypeDecls?: readonly CsgFact[];
    deferredFrameKind?: number;
    moduleLetSlots?: ReadonlyMap<string, {
        slotVar: string;
        chengType: string;
        tsType: string;
    }>;
    moduleLetUsedKeys?: Set<string>;
};
export declare function transpileFunctions(facts: readonly CsgFact[], functionNames: readonly string[], options?: TranspileR2cOptions): {
    code: string;
    results: TranspileFunctionResult[];
    structDiagnostics: string[];
    jsonStructEncoders?: string[];
    synthTypeDecls?: CsgFact[];
};
export type R2cExclusionEntry = {
    fn: string;
    class: string;
    reason: string;
};
export declare function r2cExclusionClassOf(reason: string): string;
export declare function r2cExclusionManifest(results: readonly TranspileFunctionResult[]): R2cExclusionEntry[];
export declare function transpileR2c(facts: readonly CsgFact[], componentName: string, options?: {
    hostBridges?: ReadonlyMap<string, string>;
    alwaysPrelude?: readonly string[];
}): {
    code: string;
    results: TranspileFunctionResult[];
    structDiagnostics: string[];
    slots: StateSlot[];
    slotDiagnostics: string[];
    refs: Array<{
        name: string;
        chengType: string;
        slotVar: string;
        initialExpr: string;
    }>;
    fnRefs: Array<{
        ref: string;
        alias: string;
    }>;
    refDiagnostics: string[];
    componentFound: boolean;
    exclusions: R2cExclusionEntry[];
    jsonStructEncoders?: string[];
};
export declare function emitRefSlots(facts: readonly CsgFact[], componentFunctionId: string, baseIndex?: TranspilerFactIndex, options?: {
    namePrefix?: string;
    noWrappers?: boolean;
}): {
    code: string;
    refs: Array<{
        name: string;
        chengType: string;
        slotVar: string;
        initialExpr: string;
    }>;
    fnRefs: Array<{
        ref: string;
        alias: string;
    }>;
    diagnostics: string[];
    initLines: string[];
    refused: Array<{
        name: string;
        reason: string;
    }>;
};
export {};
