#!/usr/bin/env python3
"""gen_superlinearity_fixture.py — 两尺度 emit 超线性探针的合成夹具生成器.

docs/beat-c.md §6.1.3: 同族闭包取 N 与更大尺度, 每相测 slope.
本生成器产出单文件 .cheng: N 个函数, 每个含多条 let/var 绑定 + 同文件跨函数调用
(带参带返), 定向压 typed_expr 的整程扫描热点 (PriorBindingType / ScopeIndexForLine /
ScanSourceFunctionReturnType / RhsIdentNode — 全是 "per-element 扫整程数组" 族,
函数数 N 翻倍时 O(N²) 实现必然 slope 超线性)。

seed-lint 约束: 生成代码禁冗余显式默认 init (var x: T = 0 类), var 一律裸声明。

Usage: gen_superlinearity_fixture.py <N> <out.cheng>
"""
import sys


def gen(n: int) -> str:
    lines = []
    lines.append("# AUTO-GENERATED by tools/gen_superlinearity_fixture.py — do not edit.")
    lines.append(f"# N={n} functions; cross-function calls press typed_expr whole-program scans.")
    lines.append("")
    for i in range(n):
        k1 = i % 7 + 2
        k2 = i % 11 + 1
        lines.append(f"fn SlProbeFn{i}(a: int32, b: int32): int32 =")
        lines.append(f"    let v0 = a * {k1} + b")
        lines.append("    let v1 = v0 + a - b")
        lines.append("    let v2 = v1 * 2 + v0")
        lines.append("    var acc: int32")
        lines.append(f"    acc = v2 - v1 + {k2}")
        lines.append("    let v3 = acc + v0")
        if i == 0:
            lines.append("    let c0 = v3 * 3 - acc")
            lines.append("    let c1 = c0 + v1 - b")
        else:
            lines.append(f"    let c0 = SlProbeFn{i - 1}(v3, acc)")
            lines.append(f"    let c1 = SlProbeFn{i // 2}(c0 + v1, b)")
        lines.append("    acc = acc + c0 - c1")
        lines.append("    return acc + v3")
        lines.append("")
    lines.append("fn main(): int32 =")
    lines.append(f"    let total = SlProbeFn{n - 1}(3, 7) + SlProbeFn0(1, 2)")
    lines.append("    if total == 2147480001:")
    lines.append("        return 1")
    lines.append("    return 0")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen_superlinearity_fixture.py <N> <out.cheng>\n")
        return 2
    n = int(sys.argv[1])
    if n < 1:
        sys.stderr.write("N must be >= 1\n")
        return 2
    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write(gen(n))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
