#!/usr/bin/env node
// Deterministic fixture generator for the PWA browser device DID recovery path.
//
// It is a faithful, dependency-free transcription of the derivation in
//   UniMaker/React.js/app/libp2p/browserDeviceDid.ts   (taggedHashHex, buildRecoveryPayloadText)
//   UniMaker/React.js/app/libp2p/browserPeerIdentity.ts (derivePseudoPeerId, deriveBrowserDidIdentityFromSeeds)
//
// The DID depends ONLY on recoverySecret (rootSeed = sha256(ROOT_TAG || secret)); the
// WebAuthn credential only feeds deviceSeed/peerId, so the DID is offline-reproducible.
// This node oracle and the Cheng smoke test (src/tests/bio_did_mobile_biometric_smoke.cheng)
// derive the same DID independently, breaking the double blind.
//
// Usage: node src/tests/fixtures/pwa_device_did_recovery_gen.mjs [--check]
//   (no arg) rewrites pwa_device_did_recovery_fixture.json
//   --check  recomputes and fails (exit 1) if the on-disk fixture drifts

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT_TAG = 'pwa.device.did.root.v1';
const OPERATOR_TAG = 'device.did.operator.v1';
const RECOVERY_KIND = 'unimaker_device_did_recovery_v1';
const RECOVERY_VERSION = 1;

function hexToBytes(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(bytes) {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

// taggedHashHex(tag, ...parts) = sha256(utf8(tag) || part0 || part1 ...)
function taggedHashHex(tag, ...parts) {
  const h = createHash('sha256');
  h.update(Buffer.from(tag, 'utf8'));
  for (const p of parts) h.update(Buffer.from(p));
  return h.digest('hex');
}

// fnv1a32 over a UTF-8/ASCII string, matching JS charCodeAt on ASCII input.
function fnv1a32(input) {
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i += 1) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

const PEER_ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

function derivePseudoPeerId(seed) {
  const source = seed.trim();
  let rolling = fnv1a32(`peer|${source}`);
  let body = '';
  for (let index = 0; index < 44; index += 1) {
    rolling = fnv1a32(`${source}|${index}|${rolling.toString(16)}`);
    const mixed = (rolling ^ (rolling >>> 13) ^ Math.imul(index + 1, 0x9e3779b1)) >>> 0;
    body += PEER_ALPHABET.charAt(mixed % PEER_ALPHABET.length);
  }
  return `12D3KooW${body}`;
}

function deriveDidFromRecoverySecret(recoverySecret) {
  const secretBytes = hexToBytes(recoverySecret);
  const rootSeed = taggedHashHex(ROOT_TAG, secretBytes);
  const operatorId = taggedHashHex(OPERATOR_TAG, secretBytes);
  const rootPeerId = derivePseudoPeerId(`did-root|${rootSeed}`);
  return { rootSeed, operatorId, did: `did:cheng:${rootPeerId}` };
}

// Fixed, deterministic recovery secret so the fixture is stable across runs.
const RECOVERY_SECRET = '5f1c8b3a2d4e6079a1b2c3d4e5f60718293a4b5c6d7e8f9012a3b4c5d6e7f809';

function buildFixture() {
  const { rootSeed, operatorId, did } = deriveDidFromRecoverySecret(RECOVERY_SECRET);
  const recoveryPayload = JSON.stringify(
    { kind: RECOVERY_KIND, version: RECOVERY_VERSION, operatorId, recoverySecret: RECOVERY_SECRET },
    null,
    2,
  );
  return {
    note: 'Generated by pwa_device_did_recovery_gen.mjs; do not hand-edit. Source: browserDeviceDid.ts + browserPeerIdentity.ts',
    kind: RECOVERY_KIND,
    version: RECOVERY_VERSION,
    recoverySecret: RECOVERY_SECRET,
    operatorId,
    rootSeed,
    expectedDid: did,
    recoveryPayload,
  };
}

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = join(here, 'pwa_device_did_recovery_fixture.json');
const fixture = buildFixture();
const serialized = `${JSON.stringify(fixture, null, 2)}\n`;

if (process.argv.includes('--check')) {
  const onDisk = readFileSync(fixturePath, 'utf8');
  if (onDisk !== serialized) {
    console.error('pwa device did recovery fixture drift: regenerate with pwa_device_did_recovery_gen.mjs');
    process.exit(1);
  }
  console.log('pwa device did recovery fixture ok');
} else {
  writeFileSync(fixturePath, serialized);
  console.log(`wrote ${fixturePath}`);
  console.log(`expectedDid = ${fixture.expectedDid}`);
}
