#ifndef CHENG_GUI_HOST_SHARED_H
#define CHENG_GUI_HOST_SHARED_H

// Mechanically split out of cheng_gui_host.c (slice-8 physical split, zero behavior
// change). Contains: (1) the original file-scope preamble verbatim (includes, macros,
// typedefs, struct defs) so both TUs see identical type/macro surface; (2) extern
// prototypes for the 20 functions called across the GEN/ADAPTER split (static removed
// at their single definition site, accounted in evidence.md); (3) extern declarations
// for the 39 file-scope variables touched by both sides (27 from the svars ledger +
// 12 newly-discovered fn_img_*/p_* NDK dlsym pointers), each with exactly one
// non-static definition in cheng_gui_host_gen.c.
// GENERATED by build_gui_host.sh — do not edit by hand.
// OHOS GUI host: proven Android GLES compositor body + OHOS XComponent/EGL driver.
#include <EGL/egl.h>
#include <EGL/eglext.h>
#include <GLES3/gl3.h>
#include <dlfcn.h>
#include <errno.h>
#include <limits.h>
#include <math.h>
#include <poll.h>
#include <pthread.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <arpa/inet.h>
#include <ifaddrs.h>
#include <time.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#if defined(__aarch64__) || defined(__ARM_NEON)
#include <arm_neon.h>
#define CHENG_HAS_NEON 1
#endif
#include <multimedia/player_framework/native_avcodec_base.h>
#include <multimedia/player_framework/native_avformat.h>
#include <multimedia/player_framework/native_avbuffer.h>
#include <multimedia/player_framework/native_avsource.h>
#include <multimedia/player_framework/native_avdemuxer.h>
#include <native_image/native_image.h>
#include <native_window/external_window.h>
#include <multimedia/player_framework/native_avcodec_videodecoder.h>
#include <multimedia/player_framework/avplayer.h>
#include <multimedia/player_framework/avplayer_base.h>
// #14 S8 slice1: HarmonyOS Audio ES consumption chain (OH_AudioCodec AAC/ADTS decode +
// OH_AudioRenderer low-latency output) — video-seek-scrub-blueprint.md §7.1 选项 A.
#include <multimedia/player_framework/native_avcodec_audiocodec.h>
#include <ohaudio/native_audiostream_base.h>
#include <ohaudio/native_audiostreambuilder.h>
#include <ohaudio/native_audiorenderer.h>
#include <native_vsync/native_vsync.h>
#include "ohos_android_compat.h"
#include "cheng_gui_host_adapter_contract.h"

#define CHENG_HOST_LOG_INFO(...) ((void)OH_LOG_Print(LOG_APP, LOG_INFO, 0xC000, "cheng-mobile-shell", __VA_ARGS__))
#define CHENG_HOST_LOG_ERROR(...) ((void)OH_LOG_Print(LOG_APP, LOG_ERROR, 0xC000, "cheng-mobile-shell", __VA_ARGS__))

#ifndef GL_TEXTURE_EXTERNAL_OES
#define GL_TEXTURE_EXTERNAL_OES 0x8D65
#endif

#ifndef CHENG_APP_LIB_NAME
#define CHENG_APP_LIB_NAME "cheng_gui_scene"
#endif

// RawFile forward declarations (raw_file.h is a C++ header with reference params,
// so it cannot be included into this C translation unit; we only use the C-clean
// open/read/size/close functions, declared here against the opaque types).
typedef struct NativeResourceManager NativeResourceManager;
typedef struct RawFile RawFile;
extern RawFile* OH_ResourceManager_OpenRawFile(const NativeResourceManager* mgr, const char* fileName);
extern long OH_ResourceManager_GetRawFileSize(RawFile* rawFile);
extern int OH_ResourceManager_ReadRawFile(const RawFile* rawFile, void* buf, size_t length);
extern void OH_ResourceManager_CloseRawFile(RawFile* rawFile);

// Forward decl: cheng_android_gpu_destroy (kept body) frees media textures before
// the release function is defined (in the excised media block's replacement).
struct ChengAndroidMediaTextureCache;
void cheng_android_media_texture_release(struct ChengAndroidMediaTextureCache* texture);

#define CHENG_ANDROID_WINDOW_SLOT_CAP 16
#define CHENG_ANDROID_INPUT_RING_CAPACITY (1024u * 1024u)
#define CHENG_ANDROID_INPUT_TOUCH_V1 1u
#define CHENG_ANDROID_INPUT_TOUCH_V1_BYTES 20u
#define CHENG_ANDROID_TOUCH_SCROLL_SLOP_MILLI 8000
#define CHENG_ANDROID_GPU_COMMAND_STRIDE_I32 17
#define CHENG_ANDROID_MEDIA_SURFACE_HOST_STRIDE_I32 16
#define CHENG_ANDROID_MEDIA_SURFACE_COMMAND_CAP 64
#define CHENG_ANDROID_MEDIA_TEXTURE_CACHE_CAP 64
#define CHENG_ANDROID_COMPOSITOR_LAYER_STRIDE_I32 17
#define CHENG_ANDROID_LAYER_CACHE_CAP 64
#define CHENG_ANDROID_IMAGE_ATLAS_CACHE_CAP 64
#define CHENG_ANDROID_IMAGE_ATLAS_HOST_STRIDE_I32 5
#define CHENG_ANDROID_SVG_DISPLAY_LIST_ENTRY_HOST_STRIDE_I32 3
#define CHENG_ANDROID_SVG_PRIMITIVE_HOST_STRIDE_I32 9
#define CHENG_ANDROID_PAINT_ICON_KIND_SVG 1000
#define CHENG_ANDROID_SVG_PRIMITIVE_LINE 1
#define CHENG_ANDROID_SVG_PRIMITIVE_CIRCLE 2
#define CHENG_ANDROID_SVG_PRIMITIVE_ELLIPSE 3
#define CHENG_ANDROID_SVG_PRIMITIVE_RECT 4
#define CHENG_ANDROID_SVG_PRIMITIVE_TRIANGLE 5
#define CHENG_ANDROID_SVG_COORD_UNIT 2400.0f
#define CHENG_ANDROID_SVG_STROKE_UNIT 200.0f
#define CHENG_ANDROID_GLYPH_SDF_ATLAS_CACHE_CAP 64
#define CHENG_ANDROID_GLYPH_SDF_BASE_PX_RANGE 8
#define CHENG_ANDROID_GLYPH_SDF_ATLAS_HOST_STRIDE_I32 8
#define CHENG_ANDROID_GLYPH_SDF_GLYPH_HOST_STRIDE_I32 12
#define CHENG_ANDROID_GLYPH_SDF_RUN_HOST_STRIDE_I32 6
#define CHENG_ANDROID_GLYPH_SDF_RUN_GLYPH_HOST_STRIDE_I32 2
#define CHENG_ANDROID_GPU_FILL_RECT 1
#define CHENG_ANDROID_GPU_STROKE_RECT 2
#define CHENG_ANDROID_GPU_FILL_TEXT 3
#define CHENG_ANDROID_GPU_DRAW_IMAGE 4
#define CHENG_ANDROID_GPU_DRAW_ICON 5
#define CHENG_ANDROID_GPU_SET_CLIP 6
#define CHENG_ANDROID_GPU_BOX_SHADOW 7
#define CHENG_ANDROID_GPU_GRADIENT_FILL 8
#define CHENG_ANDROID_GPU_SVG_CIRCLE_PATTERN 9
#define CHENG_ANDROID_MEDIA_SURFACE_VIDEO_FIRST_FRAME_TEXTURE 1
#define CHENG_ANDROID_MEDIA_SURFACE_IMAGE_RASTER_TEXTURE 2
#define CHENG_ANDROID_MEDIA_SURFACE_AUDIO_COVER_TEXTURE 3
#define CHENG_ANDROID_MEDIA_OBJECT_FIT_COVER 1
#define CHENG_ANDROID_MEDIA_OBJECT_FIT_CONTAIN 2
#define CHENG_ANDROID_MEDIA_OBJECT_FIT_FILL 3
#define CHENG_ANDROID_MEDIA_TEXTURE_PROVIDER_METAL_SURFACE 1
#define CHENG_ANDROID_MEDIA_TEXTURE_PROVIDER_SURFACE 2
#define CHENG_ANDROID_MEDIA_SURFACE_STATUS_NONE 0
#define CHENG_ANDROID_MEDIA_SURFACE_STATUS_PROVIDER_UNAVAILABLE 1
#define CHENG_ANDROID_MEDIA_SURFACE_STATUS_INVALID_BATCH 2
#define CHENG_ANDROID_MEDIA_SURFACE_STATUS_READY 3
#define CHENG_ANDROID_MEDIA_SURFACE_STATUS_PREPARE_FAILED 4
#define CHENG_ANDROID_MEDIA_PLAYBACK_CLOSED 0
#define CHENG_ANDROID_MEDIA_PLAYBACK_OPENED 1
#define CHENG_ANDROID_MEDIA_PLAYBACK_PLAYING 2
#define CHENG_ANDROID_MEDIA_PLAYBACK_PAUSED 3
#define CHENG_ANDROID_MEDIA_PLAYBACK_SEEKED 4
#define CHENG_ANDROID_MEDIA_TEXTURE_TARGET_EXTERNAL_OES 36197
#ifndef GL_TEXTURE_EXTERNAL_OES
#define GL_TEXTURE_EXTERNAL_OES 0x8D65
#endif
#define CHENG_ANDROID_LAYER_TRANSITION_REUSE 1
#define CHENG_ANDROID_LAYER_TRANSITION_REPLACE 2
#define CHENG_ANDROID_LAYER_TRANSITION_DROP 3
#ifndef EGL_OPENGL_ES3_BIT
#define EGL_OPENGL_ES3_BIT 0x00000040
#endif

typedef uint64_t (*cheng_app_init_fn)(void);
typedef void (*cheng_app_set_window_fn)(uint64_t, uint64_t, int, int, float);
typedef void (*cheng_app_tick_fn)(uint64_t, float);
typedef int32_t (*cheng_app_needs_frame_fn)(uint64_t);
typedef void (*cheng_app_on_touch_milli_fn)(uint64_t, int, int, int, int);
typedef int32_t (*cheng_app_on_back_fn)(uint64_t);
typedef int32_t (*cheng_app_scroll_by_fn)(uint64_t, int32_t, int32_t);
typedef int32_t (*cheng_app_ink_overlay_count_fn)(uint64_t);
typedef int32_t (*cheng_app_ink_overlay_word_fn)(uint64_t, int32_t);
typedef int32_t (*cheng_app_scroll_get_fn)(uint64_t, int32_t);
typedef void (*cheng_app_pause_fn)(uint64_t);
typedef void (*cheng_app_resume_fn)(uint64_t);
typedef int32_t (*cheng_app_text_input_utf8_fn)(const char*);
typedef int32_t (*cheng_app_media_control_fn)(uint64_t, const char*, const char*, const char*);
typedef int32_t (*cheng_app_debug_i32_fn)(void);
typedef int32_t (*cheng_app_debug_i32_at_fn)(int32_t);

typedef void (*cheng_mobile_host_runtime_set_manifest_payloads_fn)(const char*, const char*, const char*);
typedef void (*cheng_mobile_host_runtime_set_launch_args_fn)(const char*, const char*);
typedef int32_t (*cheng_mobile_host_runtime_set_state_fn)(const char*, const char*);
typedef int32_t (*cheng_mobile_host_runtime_append_string_array_state_fn)(const char*, const char*);
typedef int32_t (*cheng_mobile_host_runtime_apply_media_selection_fn)(const char*, const char*, int32_t);
typedef int32_t (*cheng_mobile_host_runtime_apply_product_csv_selection_fn)(const char*, const char*);

// wave9 phase B: typedefs for the 59 optional App exports lit up in
// cheng_resolve_exports (see cheng_gui_host_gen.c near cheng_resolve_exports
// for the full dossier reference). Signatures copied verbatim from the
// Android generator (mobile_shell_codegen.cheng MobileShellAndroidHostSource).
typedef int32_t (*cheng_app_text_input_cursor_utf8_fn)(const char*, int32_t);
typedef int32_t (*cheng_app_clear_text_input_focus_fn)(void);
typedef int32_t (*cheng_app_computer_use_compile_text_utf8_fn)(const char*, int32_t, int32_t);
typedef int32_t (*cheng_app_computer_use_gui_replay_start_fn)(int32_t);
typedef int32_t (*cheng_app_computer_use_gui_replay_tick_fn)(int32_t);
typedef char* (*cheng_app_debug_cstring_fn)(void);
typedef int32_t (*cheng_app_computer_use_media_selection_result_utf8_fn)(const char*, const char*, const char*, int64_t, int64_t, int32_t, int32_t);
typedef int32_t (*cheng_app_debug_probe2_fn)(int32_t, int32_t);
typedef int32_t (*cheng_app_debug_probe3_fn)(int32_t, int32_t, int32_t);
typedef int32_t (*cheng_app_distributed_contents_update_utf8_fn)(const char*);
typedef int32_t (*cheng_app_nodes_update_utf8_fn)(const char*);
typedef const char* (*cheng_mobile_host_runtime_current_route_state_fn)(void);
typedef const char* (*cheng_mobile_host_runtime_export_scene_state_snapshot_fn)(void);
typedef int32_t (*cheng_mobile_host_runtime_restore_scene_state_snapshot_fn)(const char*);
typedef int32_t (*cheng_mobile_host_runtime_set_storage_fn)(const char*, const char*);
typedef int32_t (*cheng_mobile_host_runtime_storage_dirty_count_fn)(void);
typedef char* (*cheng_mobile_host_runtime_storage_dirty_at_fn)(int32_t);
typedef int32_t (*cheng_mobile_host_runtime_storage_clear_dirty_fn)(const char*);

typedef struct ChengAndroidWindowSlot {
  uint64_t id;
  ANativeWindow* window;
} ChengAndroidWindowSlot;

typedef struct ChengAndroidLayerCache {
  int valid;
  int route_index;
  int layer_id;
  int origin_x;
  int origin_y;
  int width;
  int height;
  int physical_width;
  int physical_height;
  GLuint gl_texture;
} ChengAndroidLayerCache;

typedef struct ChengAndroidGlyphSdfAtlasCache {
  int valid;
  int sdf_atlas_id;
  int font_atlas_id;
  int width;
  int height;
  int pixel_count;
  int spread_px;
  int px_range;
  uint8_t* pixels;
  GLuint gl_texture;
  // bail57 root ①: multi-tile atlas fields -- present in
  // MobileShellNativeGlesCoreSource's own copy of this struct (larger SDF atlases
  // that outgrow one GL texture get tiled across gl_textures[]) but dropped from
  // this shared header's copy; union merge so a single authoritative definition
  // covers both call sites.
  GLuint* gl_textures;
  int gl_texture_count;
  int gl_tile_height;
  int gl_uploaded;
} ChengAndroidGlyphSdfAtlasCache;

typedef struct ChengAndroidGlyphSdfGlyphCache {
  int glyph_id;
  int sdf_atlas_id;
  int atlas_x;
  int atlas_y;
  int width;
  int height;
  int advance;
  int font_atlas_id;
  int sdf_pixel_start;
  int sdf_pixel_count;
  int codepoint;
  int font_size;
} ChengAndroidGlyphSdfGlyphCache;

typedef struct ChengAndroidGlyphSdfRunCache {
  int glyph_run_id;
  int font_atlas_id;
  int sdf_atlas_id;
  int glyph_start;
  int glyph_count;
  int advance_width;
} ChengAndroidGlyphSdfRunCache;

typedef struct ChengAndroidGlyphSdfRunGlyphCache {
  int glyph_id;
  int advance;
} ChengAndroidGlyphSdfRunGlyphCache;

typedef struct ChengAndroidImageTextureCache {
  int valid;
  int texture_id;
  int width;
  int height;
  int pixel_count;
  uint8_t* pixels;
  GLuint gl_texture;
  int gl_uploaded;
  // bail57 root ①: present in MobileShellNativeGlesCoreSource's own copy of this
  // struct (marks textures re-uploaded every frame, e.g. video posters swapped
  // live) but dropped from this shared header's copy; union merge.
  int dynamic_texture;
} ChengAndroidImageTextureCache;

typedef struct ChengAndroidMediaTextureCache {
  int valid;
  int kind_code;
  int surface_kind;
  int texture_provider;
  int slot_hash;
  int asset_hash;
  int manifest_hash;
  int poster_hash;
  int width;
  int height;
  int pixel_format;
  int texture_target;
  GLuint gl_texture;
  float texture_transform[16];
  int texture_transform_valid;
  int rotation_degrees;
  jobject surface_texture;
  jobject surface;
  ANativeWindow* decode_window;
  AMediaExtractor* extractor;
  AMediaCodec* codec;
  int decoder_started;
  int input_done;
  int output_done;
  int frame_count;
  int update_count;
  int64_t last_presentation_us;
  int last_playback_state;
  char asset_rel[160];
  // Frame-paced video playback: an ordered set of decoded frame textures played
  // back at video_fps, looping. gl_texture mirrors the current frame for the
  // first-frame 秒开 + any single-texture draw path. (Legacy decode-all model;
  // superseded by the MoQ streaming model below for the video card.)
  GLuint* video_frames;
  int video_frame_count;
  int video_fps;
  int64_t video_start_ns;
  // MoQ progressive streaming: a live decoder fed by a QUIC byte-range data source
  // produces RGBA frames into a bounded ring; the render thread consumes one per
  // frame period (video_fps) into a single reused texture. Bounded memory, length-
  // independent, looping.
  struct ChengStreamCtx* stream_ctx;
  GLuint video_tex;
  int video_tex_w;
  int video_tex_h;
  int64_t last_consume_ns;
} ChengAndroidMediaTextureCache;

// MoQ progressive streaming decode context. Lives on the heap (the OHOS codec
// thread keeps producing into the ring after prepare returns); the render thread
// consumes. Held by ChengAndroidMediaTextureCache.stream_ctx, torn down on release.
#define CHENG_STREAM_RING_CAP 6
// Deep input FIFO so the periodic per-batch dial (~1s cross-device handshake) is
// absorbed without starving the decoder: at 30fps the decoder drains ~30 frames
// during one dial, so the FIFO must hold more than that (>= one batch worth).
#define CHENG_STREAM_FQ_CAP 128
// MoQ per-frame streaming: the publisher pre-demuxes the mp4 into an Annex-B
// elementary stream; the render thread fetches one access unit per frame over QUIC
// (small, survives the loss-recovery-less transport) into the input FIFO, and the
// codec's onNeedInputBuffer drains it straight into the decoder. No OH_AVSource /
// random-access readAt (large transfers stall cross-device).
typedef struct ChengStreamCtx {
  OH_AVCodec* dec;
  int w, h;
  double fps;
  int frame_count;
  int es_rotation;               // normalized display rotation from the current index
  int next_frame_idx;            // render-thread prefetch cursor (loops at frame_count)
  pthread_mutex_t mu;            // output RGBA ring
  pthread_cond_t cv_notfull;     // output ring not-full (producer backpressure)
  unsigned char* ring[CHENG_STREAM_RING_CAP];
  int ring_head, ring_tail, ring_size;
  // input prefetch FIFO: render thread fills (QUIC, single-threaded Cheng runtime),
  // codec onNeedInputBuffer drains. The codec WAITS on cv_notempty for a frame (a
  // codec that gets an input-buffer offer with no frame and returns without pushing
  // loses that offer and starves). One-directional wait (render fills+signals, never
  // waits on the codec) → no deadlock.
  pthread_mutex_t fq_mu;
  pthread_cond_t cv_notempty;
  pthread_cond_t cv_notfull_fq;  // input FIFO not-full (persistent-conn producer backpressure)
  unsigned char* fq[CHENG_STREAM_FQ_CAP];
  int32_t fq_len[CHENG_STREAM_FQ_CAP];
  int64_t fq_pts[CHENG_STREAM_FQ_CAP];
  int fq_key[CHENG_STREAM_FQ_CAP];
  int fq_head, fq_tail, fq_size;
  // RGBA frame-buffer pool: malloc(w*h*4) per frame faults in ~3072 fresh pages
  // (~30ms of kernel zero-fill) which dominated conversion. Pre-allocate + pre-fault
  // a small pool once and recycle, so steady-state conversion is pure compute. Managed
  // as a free-list stack (pool[0..pool_top-1] available) under `mu`.
  unsigned char* pool[CHENG_STREAM_RING_CAP + 2];
  int pool_top;
  size_t frame_bytes;
  int stop;
  // #14-eos: set once by the fetch thread (cheng_stream_mark_video_input_done) when the
  // network ES pump has reached the last frame (WebSceneMediaEsStreamLoop rc==7) — mirrors
  // ChengAudioEsStreamCtx.input_done below. Read by cheng_stream_on_need_input (the codec's
  // own callback thread) to push an EOS buffer instead of waiting forever for a frame that
  // will never arrive. Reset to 0 on seek (cheng_stream_apply_seek).
  int input_done;
  // S5-B pause/resume backpressure gateway (video-seek-scrub-blueprint.md §7.4): set by
  // ANY thread (e.g. the render thread on a UI pause) under fq_mu; read+mirrored into the
  // Cheng bridge's own paused flag ONLY by the fetch thread (cheng_stream_fetch_worker,
  // the single thread allowed to call the QUIC bridge — see cheng_scene_media_es_set_paused
  // in scene-runtime-smoke-source.mjs). Reuses cv_notfull_fq to wake a backed-off fetch
  // thread promptly on resume or teardown, same as the existing FIFO/stop wakeups.
  int paused_requested;
  // S3a seek request handoff (video-seek-scrub-blueprint.md §S3a): set by ANY thread
  // (e.g. the render thread on a UI drag-seek, via cheng_host_video_seek) under fq_mu —
  // same handoff shape as paused_requested above. Consumed by whichever thread owns this
  // stream's decode pipeline: the network path's fetch thread (cheng_stream_fetch_worker,
  // which forwards the target to the Cheng bridge's WebSceneMediaEsSeekToPositionMs before
  // applying the local reset) or the local-file path's own worker
  // (cheng_stream_local_file_worker, which owns `demux` and calls OH_AVDemuxer_SeekToTime
  // directly — `demux` is a worker-local variable, not reachable from another thread).
  // Both call the shared cheng_stream_apply_seek() to drain fq/ring, OH_VideoDecoder_Flush,
  // and reset the pts/play-clock globals. Reuses cv_notfull_fq for the wakeup, same as
  // paused_requested.
  int seek_requested;
  int32_t seek_target_ms;
  // Seek-epoch race gate (v2 hardening, see cheng_stream_apply_seek/cheng_stream_on_new_output):
  // guards the ZERO-COPY surface path, which the fq/ring drain above cannot reach — the decode
  // callback there renders straight to the OES surface with no queue to retroactively purge.
  // seek_epoch is bumped under mu as the very first statement of cheng_stream_apply_seek
  // (before the fq/ring drain or OH_VideoDecoder_Flush); seek_epoch_flushed is set to match
  // (also under mu) only after OH_VideoDecoder_Flush returns. The two differ for exactly the
  // window a seek is being applied; the output callback drops (FreeOutputBuffer, not leaked)
  // any frame it sees while they differ instead of compositing it. Both fields are only ever
  // read/written under mu, same as ring_head/ring_tail/pool_top above.
  int32_t seek_epoch;
  int32_t seek_epoch_flushed;
} ChengStreamCtx;

// One shared streaming decode for the video card(s) — started on a BACKGROUND
// thread (cheng_stream_start_worker) so the synchronous QUIC session open + moov
// reads NEVER block the render thread (a stalled dial would otherwise freeze the
// whole GUI). The render thread consumes frames into s_stream_tex once
// s_stream_ready flips; all video cards draw that one texture.

// OHOS image NDK via dlopen (NOT DT_NEEDED). libimage_source.so / libpixelmap.so
// are not in this app's DEFAULT linker namespace, so a hard link makes the whole
// .so fail to load. dlopen (which can resolve via the system namespace / full
// path) lets the .so load regardless and decode best-effort: if it resolves, the
// poster decodes to a real texture; if not, the caller keeps a placeholder.
typedef struct OH_ImageSourceNative OH_ImageSourceNative;
typedef struct OH_DecodingOptions OH_DecodingOptions;
typedef struct OH_PixelmapNative OH_PixelmapNative;
typedef struct OH_Pixelmap_ImageInfo OH_Pixelmap_ImageInfo;
#define CHENG_PIXEL_FORMAT_RGBA_8888 3
#define CHENG_IMAGE_SUCCESS 0
typedef int (*fn_img_CreateFromFd)(int32_t, OH_ImageSourceNative**);
typedef int (*fn_img_CreatePixelmap)(OH_ImageSourceNative*, OH_DecodingOptions*, OH_PixelmapNative**);
typedef int (*fn_img_SrcRelease)(OH_ImageSourceNative*);
typedef int (*fn_dopt_Create)(OH_DecodingOptions**);
typedef int (*fn_dopt_SetPixelFormat)(OH_DecodingOptions*, int32_t);
typedef int (*fn_dopt_Release)(OH_DecodingOptions*);
typedef int (*fn_iinfo_Create)(OH_Pixelmap_ImageInfo**);
typedef int (*fn_pm_GetImageInfo)(OH_PixelmapNative*, OH_Pixelmap_ImageInfo*);
typedef int (*fn_iinfo_GetU32)(OH_Pixelmap_ImageInfo*, uint32_t*);
typedef int (*fn_iinfo_Release)(OH_Pixelmap_ImageInfo*);
typedef int (*fn_pm_ReadPixels)(OH_PixelmapNative*, uint8_t*, size_t*);
typedef int (*fn_pm_Release)(OH_PixelmapNative*);

// ---- fn_img_*/OH_Image* NDK typedefs relocated here verbatim (4588-4605): shared by
// cheng_img_ndk_load (adapter, dlsym) and cheng_ohos_decode_image_rgba (gen, calls). ----

// ---- cross-file function prototypes (static removed at definition site) ----
extern void cheng_android_gpu_draw_rect(int screen_width, int screen_height, int x, int y, int width, int height, uint32_t argb, int radius);
extern void cheng_android_gpu_draw_video_back_overlay(int screen_width, int screen_height);
extern void cheng_android_media_texture_release(ChengAndroidMediaTextureCache* texture);
extern int cheng_android_normalize_video_rotation_degrees(int rotation_degrees);
extern void cheng_audio_es_apply_seek(int32_t newAudioFrameIdx);
extern int cheng_audio_es_engage(int32_t sample_rate, int32_t channels, int32_t frame_count);
extern void cheng_audio_es_mark_input_done(void);
extern void cheng_audio_es_prefetch_push(int32_t frame_idx, const unsigned char* src, int32_t frame_size);
extern void cheng_audio_es_stop_at_eos(void);
extern void cheng_audio_es_teardown(void);
extern void cheng_audio_on_info(OH_AVPlayer* player, AVPlayerOnInfoType type, OH_AVFormat* infoBody, void* userData);
extern void cheng_audio_play_local_file(const char* path, int looping);
extern void cheng_dec_on_error(OH_AVCodec* c, int32_t e, void* u);
extern void cheng_dec_on_stream_changed(OH_AVCodec* c, OH_AVFormat* f, void* u);
extern void cheng_endurance_report(const char* reason);
extern GLuint cheng_gl_compile_shader(GLenum type, const char* src);
extern char* cheng_gui_read_rawfile_text(const char* rel);
extern int cheng_host_extract_rawfile_to_cache(const char* name);
extern int cheng_img_ndk_load(void);
extern void cheng_media_diag(const char* line);
extern int64_t cheng_monotime_ns(void);
extern void cheng_nv12_to_rgba_into(unsigned char* rgba, const uint8_t* nv12, int w, int h, int stride, int slice);
extern void* cheng_ohos_resource_manager(void);
extern ChengStreamCtx* cheng_ohos_start_streaming_decode(int w, int h, double fps, int frame_count);
extern void* cheng_publish_port_reporter(void* arg);
extern int64_t cheng_read_rss_kb(void);
extern void cheng_stream_apply_seek(ChengStreamCtx* sc);
extern void* cheng_stream_local_file_worker(void* arg);
extern void cheng_stream_mark_video_input_done(ChengStreamCtx* sc);
extern void cheng_stream_on_need_input(OH_AVCodec* c, uint32_t index, OH_AVBuffer* buffer, void* u);
extern void* cheng_stream_prewarm_worker(void* arg);
extern void cheng_stream_teardown_active(void);
extern int cheng_surface_consume(int w, int h);  // 1 = a real frame was consumed+drawn this call (修5 2026-07-26: 秒开 t1 must not count a no-op)
extern int cheng_surface_create_oes(void);
extern void cheng_video_vsync_disengage(void);

// ---- cross-file shared variables (static removed at definition site in
// cheng_gui_host_gen.c) ----
extern ChengStreamCtx* s_stream_ctx;
extern volatile int s_stream_starting;
extern volatile int s_fetch_route;
extern OH_AVPlayer* s_audio_player;
extern volatile int s_stream_ready;
extern GLuint s_stream_tex;
extern int64_t s_stream_play_base_ns;
extern int64_t s_stream_last_frame_idx;
extern volatile int s_stream_paused;
extern volatile int s_surf_mode;
extern OHNativeWindow* s_surf_window;
extern volatile int s_fetch_thread_started;
extern pthread_t s_fetch_thread;
extern volatile int s_stream_src_eof;
extern volatile int s_stream_eos;
extern int s_stream_eos_logged;
extern int s_stream_prefetch_total;  // cumulative video AUs produced by the pump (adapter.c); 修3 gates the deferred audio open on it
// Publish-receipt mailbox (gen.c, 2026-07-26 init-race root fix): background reporter posts, render thread drains.
extern void cheng_host_publish_receipt_post(const char* cid, int port);
extern void cheng_host_publish_receipt_drain(void);
/* S3 feed prewarm plan: up to N=2 visible-card peers (host dials first only —
   single global ES session; second peer is plan/diag until per-slot pool lands). */
#define CHENG_FEED_PREWARM_N 2
extern char s_prewarm_peer_host[64]; /* alias of plan[0] for legacy readers */
extern volatile int s_prewarm_peer_port;
extern char s_prewarm_hosts[CHENG_FEED_PREWARM_N][64];
extern int s_prewarm_ports[CHENG_FEED_PREWARM_N];
extern volatile int s_prewarm_plan_count;
extern volatile int s_prewarm_started;
extern ChengAndroidMediaTextureCache* s_active_stream_texture;
extern int s_video_back_btn_x;
extern int s_video_back_btn_y;
extern int s_video_back_btn_w;
extern int s_video_back_btn_h;
extern cheng_app_pause_fn       s_gui_app_pause;
extern uint64_t s_gui_app_id;
extern void* s_gui_resource_manager;
extern fn_img_CreateFromFd p_CreateFromFd;
extern fn_img_CreatePixelmap p_CreatePixelmap;
extern fn_img_SrcRelease p_SrcRelease;
extern fn_dopt_Create p_DoptCreate;
extern fn_dopt_SetPixelFormat p_DoptSetPixelFormat;
extern fn_dopt_Release p_DoptRelease;
extern fn_iinfo_Create p_IInfoCreate;
extern fn_pm_GetImageInfo p_GetImageInfo;
extern fn_iinfo_GetU32 p_GetWidth, p_GetHeight, p_GetRowStride;
extern fn_iinfo_Release p_IInfoRelease;
extern fn_pm_ReadPixels p_ReadPixels;
extern fn_pm_Release p_PmRelease;

// ---- CHENG_LEAK_AUDIT: opt-in per-point malloc/free byte accounting on the
// playback path (native_hook attribution instrument, see leak3/evidence.md).
// Compiled out entirely (zero code, zero storage) unless CHENG_LEAK_AUDIT is
// defined at build time (-DCHENG_LEAK_AUDIT=1). Named points cover every
// malloc/calloc call site reachable from LOCAL-file playback plus the
// cheng_malloc/cheng_free Cheng-runtime allocator boundary (catches Cheng-side
// struct-copy churn from any call site, not just the ones hand-audited so far).
#ifdef CHENG_LEAK_AUDIT
#include <malloc.h>  // malloc_usable_size: exact freed-byte size for net-outstanding accounting
typedef enum {
  CHENG_LEAK_PT_STREAM_CTX_CALLOC = 0,   // adapter.c cheng_ohos_start_streaming_decode: calloc(1,sizeof(ChengStreamCtx)), per-prepare
  CHENG_LEAK_PT_CPU_RING_POOL_MALLOC,    // adapter.c: CPU-fallback RGBA pool malloc(frame_bytes) x(RING_CAP+2), only when s_surf_mode=0
  CHENG_LEAK_PT_ES_PREFETCH_MALLOC,      // adapter.c cheng_stream_prefetch_frames: malloc(CHENG_STREAM_MAXFRAME), network ES path only
  CHENG_LEAK_PT_ES_SINK_MALLOC,          // adapter.c cheng_scene_media_es_sink_frame: malloc(frameSize), network ES path only
  CHENG_LEAK_PT_LOCAL_PUSH_FRAME_MALLOC, // adapter.c cheng_stream_local_push_frame: malloc(n), LOCAL path, every NALU
  CHENG_LEAK_PT_ON_NEED_INPUT_FREE,      // gen.c cheng_stream_on_need_input: free(bytes), pairs with LOCAL_PUSH_FRAME_MALLOC
  CHENG_LEAK_PT_DECODE_FIRST_FRAME_MALLOC, // gen.c cheng_ohos_decode_first_frame: ctx->nv12 malloc, once per prepare
  CHENG_LEAK_PT_DECODE_FIRST_FRAME_FREE,   // gen.c: matching free(ctx.nv12)
  CHENG_LEAK_PT_CHENG_MALLOC,            // gen.c cheng_malloc: aggregate Cheng-runtime allocator entry (all Cheng-side heap allocs)
  CHENG_LEAK_PT_CHENG_FREE,              // gen.c cheng_free: aggregate Cheng-runtime allocator exit
  CHENG_LEAK_PT_COUNT
} ChengLeakAuditPoint;

extern volatile int64_t g_cheng_leak_audit_calls[CHENG_LEAK_PT_COUNT];
extern volatile int64_t g_cheng_leak_audit_bytes[CHENG_LEAK_PT_COUNT];

// Records one alloc/free event at the given named point (thread-safe, lock-free).
extern void cheng_leak_audit_record(ChengLeakAuditPoint point, int64_t bytes);
// Call once per render tick. Internally wall-clock gated (cheng_monotime_ns): a
// no-op on every call except roughly once per 5s, when it emits one structured
// hilog line via cheng_media_diag with interval deltas + cumulative + net
// outstanding (malloc_bytes - free_bytes) for the two paired points.
extern void cheng_leak_audit_tick(void);

#define CHENG_LEAK_AUDIT_RECORD(point, bytes) cheng_leak_audit_record((point), (int64_t)(bytes))
#define CHENG_LEAK_AUDIT_TICK() cheng_leak_audit_tick()
#else
#define CHENG_LEAK_AUDIT_RECORD(point, bytes) ((void)0)
#define CHENG_LEAK_AUDIT_TICK() ((void)0)
#endif // CHENG_LEAK_AUDIT

#endif // CHENG_GUI_HOST_SHARED_H
