// GENERATED by src/core/tooling/mobile_shell_codegen.cheng (MobileShellHarmonyAdapterContractText).
// Do not edit by hand. See docs/harmony-host-codegen-migration-plan.md, "slice-7
// 执行勘误" section, for the design and the audit scripts that keep this file honest.
//
// This header models the ABI contract at
// platform/harmony/ChengGuiDemo/entry/src/main/cpp/cheng_gui_host.c as two
// independent tables, because the two directions are enforced differently:
//
//   GLUE       host.c DEFINES these functions (external linkage). The App-side
//              generated Cheng scene and cheng_gui_entry.cpp's NAPI glue call
//              them by name. Declaring the signatures here as `extern` and
//              having host.c #include this header turns a signature drift
//              between this contract and host.c's real definition into a hard
//              compile error ("conflicting types"), not a runtime surprise.
//
//   APP-EXPORT the reverse direction: the App core (the generated Cheng scene
//              .so) exports these; host.c resolves each one at runtime via
//              dlsym(s_app_handle, "name") on purpose (soft-optional linking —
//              host.c must keep loading older scene .o builds that predate a
//              given export, so a hard extern here would be wrong, not just
//              unnecessary). dlsym cannot be compile-checked against the real
//              symbol, so this section is instead the single canonical
//              function-pointer typedef for every dlsym cast site of that name
//              in host.c: every cast site must use the typedef declared here
//              (not a locally re-typed one), so an intentional signature edit
//              breaks every call site at once at compile time instead of one
//              drifting silently out of sync with the others.
//
// Two contract-shaped things are intentionally NOT declared below:
//
//   - cheng_host_read_asset is `static` (internal linkage) in host.c — a
//     rawfile-asset read helper called only from within the same translation
//     unit (cheng_gui_host_gen.c). It is one of the 33 cheng_host_* function
//     definitions in host.c today, but it is not part of the adapter-facing
//     ABI surface: no other translation unit can call it. A non-static
//     `extern` declaration here would conflict with its `static` definition
//     and break every host.c compile outright, not just a real signature
//     drift, so it is deliberately left out of the GLUE table (32 entries
//     below + this 1 documented internal-linkage gap = 33). Note:
//     cheng_host_extract_rawfile_to_cache used to be documented here too —
//     the slice-8 physical split (cheng_gui_host_gen.c + _adapter.c) made it
//     genuinely cross-TU (cheng_gui_host_adapter.c calls it), so it lost its
//     `static` and is now a real GLUE entry below, not a documented gap.
//
//   - cheng_mobile_host_present / cheng_mobile_host_end_offscreen_capture are
//     GEN-side symbols with zero occurrences in the current host.c (grep
//     confirmed) — they are a slice-3/slice-6 GEN convergence item, not an
//     ADAPTER contract signature, so they do not belong in either table here.
//
// Two more ABI-shaped things are out of scope for THIS header on purpose:
//
//   - cheng_host_open_file_picker / cheng_gui_host_file_picker_deliver's
//     result_mode parameter is not a free string — it is a closed 9-state
//     set: "" (no payload) | "uri" | "name" | "text" | "product-csv" |
//     "data-url" | "data-url-array-append" | "media-selection" | "qr-text".
//     Re-grepped end to end for THIS header, not copied from an older recon
//     note: the Android generator dispatches "qr-text" one level above
//     chengFilePickerPayload (mobile_shell_codegen.cheng ~6560, before the
//     7-branch payload switch at ~1877-1901 — re-grep both before trusting a
//     line number), and Harmony's cheng_gui_host_file_picker_deliver
//     (cheng_gui_host.c ~7238-7344) special-cases "qr-text" the same way
//     before its own 7-branch switch — so the true closed set is 8 non-empty
//     values, not 7; a value-set audit that only reads chengFilePickerPayload
//     undercounts by one. A C string parameter cannot be compile-checked
//     against a value set, so this header only fixes the *signature*
//     (const char* result_mode); the *value* contract is cross-checked by
//     tools/harmony_adapter_contract_diff.sh's picker-mode section, not by
//     the C compiler.
//
//   - publish_trace's three hilog markers (t_pub0/t_pub1/t_pub2 in host.c, and
//     their Android JNI-bridge counterpart) are a runtime oracle contract
//     (§7 acceptance definition), not a compile-time ABI signature — matched
//     by human/oracle-script log-field inspection, not by this header.
//
#ifndef CHENG_GUI_HOST_ADAPTER_CONTRACT_H
#define CHENG_GUI_HOST_ADAPTER_CONTRACT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * GLUE — host.c defines (external linkage); adapter/App-generated glue calls.
 * 32 declared signatures. (33rd cheng_host_* definition in host.c,
 * cheng_host_read_asset, is `static` — see file header above.)
 * ==========================================================================*/

void cheng_host_es_diag(int32_t step, int32_t a, int32_t b);
void cheng_host_video_pause(void);
void cheng_host_video_play(void);
int32_t cheng_host_video_paused(int32_t handle);
void cheng_host_video_play_slot(int32_t handle);
void cheng_host_video_pause_slot(int32_t handle);
void cheng_host_video_seek(int32_t handle, int32_t position_ms);
void cheng_host_video_set_muted(int32_t handle, int32_t muted);
int32_t cheng_host_fullscreen_active(void);
void cheng_host_request_fullscreen(void);
void cheng_host_exit_fullscreen(void);
void cheng_host_open_file_picker(const char* ref_name, const char* kind, const char* result_mode, const char* result_state_ref);
const char* cheng_host_capture_location(int32_t timeout_ms, int32_t max_age_ms, const char* preview_ref, const char* status_ref, const char* message_ref);
int32_t cheng_host_open_content_location(const char* content_json);
const char* cheng_host_social_groups_create(const char* group_meta_json);
const char* cheng_host_social_synccast_control(const char* room_id, const char* op);
const char* cheng_host_social_synccast_refresh(const char* room_id);
const char* cheng_host_region_policy_refresh(void);
const char* cheng_host_profile_peer_id_refresh(void);
const char* cheng_host_profile_asset_action_submit(const char* request_json);
const char* cheng_host_node_contents_refresh(const char* peer_id, int32_t use_network);
const char* cheng_host_nodes_snapshot_refresh(void);
const char* cheng_host_clear_published_contents(const char* peer_id);
const char* cheng_host_content_delete(const char* content_json, const char* confirm_message);
const char* cheng_host_profile_bio_did_create(void);
const char* cheng_host_profile_bio_did_import(const char* recovery_raw);
const char* cheng_host_trading_refresh(const char* pair_json, const char* interval);
const char* cheng_host_rwad_nfc_receive_toggle(const char* wallet_id, int32_t active);
void cheng_host_publish(const char* selected_media_path, const char* publish_kind, const char* publish_payload_json);
void cheng_host_clipboard_write_text(const char* text);
int cheng_host_extract_rawfile_to_cache(const char* name);
void cheng_host_start_own_serve(void);

/* ============================================================================
 * APP-EXPORT — App core exports; host.c resolves via dlsym(s_app_handle, ...)
 * (a few resolve via dlsym(RTLD_DEFAULT, ...) instead — same App .so, same
 * contract). 138 canonical function-pointer typedefs, one per dlsym'd symbol
 * name (grep-exhaustive over host.c's dlsym( call sites).
 * ==========================================================================*/

/* -- app lifecycle / frame-drive / input (uint64_t appId handle) ---------- */
typedef uint64_t (*cheng_gui_host_contract_cheng_app_init_fn)(void);
typedef void (*cheng_gui_host_contract_cheng_app_set_window_fn)(uint64_t appId, uint64_t window, int width, int height, float density);
typedef void (*cheng_gui_host_contract_cheng_app_tick_fn)(uint64_t appId, float dt);
typedef int32_t (*cheng_gui_host_contract_cheng_app_needs_frame_fn)(uint64_t appId);
typedef void (*cheng_gui_host_contract_cheng_app_on_touch_milli_fn)(uint64_t appId, int phase, int reserved, int xMilli, int yMilli);
typedef int32_t (*cheng_gui_host_contract_cheng_app_on_back_fn)(uint64_t appId);
typedef int32_t (*cheng_gui_host_contract_cheng_app_scroll_by_fn)(uint64_t appId, int32_t nodeId, int32_t deltaMilli);
typedef int32_t (*cheng_gui_host_contract_cheng_app_scroll_get_fn)(uint64_t appId, int32_t nodeId);
typedef void (*cheng_gui_host_contract_cheng_app_pause_fn)(uint64_t appId);
typedef void (*cheng_gui_host_contract_cheng_app_resume_fn)(uint64_t appId);
typedef int32_t (*cheng_gui_host_contract_cheng_app_text_input_utf8_fn)(const char* utf8);
typedef int32_t (*cheng_gui_host_contract_cheng_app_media_control_fn)(uint64_t appId, const char* slot, const char* action, const char* payload);
typedef int32_t (*cheng_gui_host_contract_cheng_app_ink_overlay_command_count_fn)(uint64_t appId);
typedef int32_t (*cheng_gui_host_contract_cheng_app_ink_overlay_command_word_fn)(uint64_t appId, int32_t index);

/* -- mobile_host_runtime bootstrap (manifest / launch args / state) ------- */
typedef void (*cheng_gui_host_contract_cheng_mobile_host_runtime_set_manifest_payloads_fn)(const char* contractJson, const char* bundleJson, const char* extra);
typedef void (*cheng_gui_host_contract_cheng_mobile_host_runtime_set_launch_args_fn)(const char* kvText, const char* jsonText);
typedef int32_t (*cheng_gui_host_contract_cheng_mobile_host_runtime_set_state_fn)(const char* key, const char* valueJson);
typedef int32_t (*cheng_gui_host_contract_cheng_mobile_host_runtime_append_string_array_state_fn)(const char* key, const char* valueJson);
typedef int32_t (*cheng_gui_host_contract_cheng_mobile_host_runtime_apply_media_selection_fn)(const char* key, const char* valueJson);
typedef int32_t (*cheng_gui_host_contract_cheng_mobile_host_runtime_apply_product_csv_selection_fn)(const char* key, const char* valueJson);

/* -- prewarmed media-slot ES bridge (content-addressing verify) ----------- */
typedef int32_t (*cheng_gui_host_contract_cheng_scene_media_es_rotation_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_scene_media_es_content_matches_fn)(const char* expectedContentId);
typedef int32_t (*cheng_gui_host_contract_cheng_scene_media_es_invalidate_fn)(void);

/* -- debug/diagnostic counters, no-arg int32_t getters --------------------
 * All of these share the shape int32_t(void); each still gets its own named
 * typedef (rather than one shared alias) so an intentional signature change
 * to exactly one counter cannot silently widen to the other 45 by accident. */
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_last_main_status_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_build_step_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_layout_fail_code_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_layout_fail_route_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_layout_fail_node_id_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_layout_fail_ordinal_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_css_fail_code_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_css_fail_route_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_css_fail_node_id_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_css_fail_rule_ordinal_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_css_fail_declaration_ordinal_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_css_fail_property_code_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_svg_atlas_fail_code_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_svg_atlas_fail_paint_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_svg_atlas_fail_route_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_svg_atlas_fail_node_id_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_svg_atlas_fail_ordinal_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_svg_atlas_fail_resource_hash_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_glyph_atlas_fail_code_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_glyph_atlas_fail_route_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_glyph_atlas_fail_node_id_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_glyph_atlas_fail_ordinal_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_glyph_atlas_fail_codepoint_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_gpu_command_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_surface_command_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_surface_batch_bytes_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_surface_batch_stride_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_receipt_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_compositor_layer_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_refresh_css_fail_stage_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_route_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_touch_hit_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_last_event_hit_node_id_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_last_event_hit_status_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_last_event_apply_status_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_state_publish_notice_open_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_state_is_original_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_state_is_paid_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_state_show_review_console_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_focused_text_route_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_focused_text_node_id_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_video_guard_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_video_node_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_slot_count_all_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_active_route_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_video_cmd_added_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_video_cmd_node_fn)(void);

/* -- debug/diagnostic counters, indexed int32_t(int32_t) getters ---------- */
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_receipt_action_code_at_fn)(int32_t index);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_receipt_status_at_fn)(int32_t index);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_receipt_state_at_fn)(int32_t index);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_receipt_kind_at_fn)(int32_t index);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_media_receipt_audio_provider_hash_at_fn)(int32_t index);

/* -- text input (utf8 cursor state, focus clear) --------------------------- */
typedef int32_t (*cheng_gui_host_contract_cheng_app_clear_text_input_focus_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_text_input_cursor_utf8_fn)(const char* utf8, int32_t cursorByteLen);

/* -- computer-use (small-model GUI replay/compile bridge) ------------------ */
typedef int32_t (*cheng_gui_host_contract_cheng_app_computer_use_compile_text_utf8_fn)(const char* text, int32_t a, int32_t b);
typedef int32_t (*cheng_gui_host_contract_cheng_app_computer_use_gui_replay_start_fn)(int32_t templateCode);
typedef int32_t (*cheng_gui_host_contract_cheng_app_computer_use_gui_replay_tick_fn)(int32_t slowPermille);
typedef int32_t (*cheng_gui_host_contract_cheng_app_computer_use_media_selection_result_with_preview_utf8_fn)(const char* uri, const char* name, const char* localPath, int64_t sizeBytes, int64_t durationMs, int32_t width, int32_t height);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_execution_mode_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_current_slow_permille_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_gui_replay_active_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_gui_replay_step_index_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_gui_replay_step_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_gui_replay_applied_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_gui_replay_last_status_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_chat_trigger_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_chat_result_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_status_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_template_code_fn)(void);
typedef char* (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_title_utf8_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_title_byte_len_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_distance_km_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_media_status_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_media_uri_byte_len_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_media_name_byte_len_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_computer_use_last_media_local_path_byte_len_fn)(void);

/* -- distributed-nodes tab (peer list / content-card top/route probes) ----- */
typedef int32_t (*cheng_gui_host_contract_cheng_app_distributed_contents_update_utf8_fn)(const char* json);
typedef int32_t (*cheng_gui_host_contract_cheng_app_nodes_update_utf8_fn)(const char* json);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_nodes_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_shown_count_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_top_kind_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_top_node_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_top_apply_status_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_route_apply_from_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_route_apply_to_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_route_apply_node_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_route_apply_target_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_route_apply_status_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_route_is_fullscreen_video_fn)(int32_t routeIndex);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_node_box_fn)(int32_t a, int32_t b);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_route_hit_probe_fn)(int32_t a, int32_t b);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_box_probe_fn)(int32_t a, int32_t b, int32_t c);

/* -- fullscreen-video / route state diagnostics ----------------------------- */
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_state_is_video_playing_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_video_overlay_hidden_fn)(void);

/* -- m2 (content detail rebind) debug counters ------------------------------ */
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_contents_len_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_shown_len_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_title_len_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_media_len_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_media_kind_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_media_is_local_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_rebind_changed_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_rebind_applied_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_first_category_content_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_app_debug_m2_active_category_content_fn)(void);

/* -- mobile_host_runtime scene-state persistence / storage-dirty bridge ---- */
typedef const char* (*cheng_gui_host_contract_cheng_mobile_host_runtime_current_route_state_fn)(void);
typedef const char* (*cheng_gui_host_contract_cheng_mobile_host_runtime_export_scene_state_snapshot_utf8_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_mobile_host_runtime_restore_scene_state_snapshot_utf8_fn)(const char* json);
typedef int32_t (*cheng_gui_host_contract_cheng_mobile_host_runtime_set_storage_fn)(const char* key, const char* valueJson);
typedef int32_t (*cheng_gui_host_contract_cheng_mobile_host_runtime_storage_clear_dirty_fn)(const char* key);
typedef int32_t (*cheng_gui_host_contract_cheng_mobile_host_runtime_storage_dirty_count_fn)(void);
typedef char* (*cheng_gui_host_contract_cheng_mobile_host_runtime_storage_dirty_key_utf8_fn)(int32_t index);
typedef char* (*cheng_gui_host_contract_cheng_mobile_host_runtime_storage_dirty_value_utf8_fn)(int32_t index);

/* -- prewarmed media-slot ES bridge (error text / pause / seek control) ---- */
typedef const char* (*cheng_gui_host_contract_cheng_scene_media_es_last_error_fn)(void);
typedef int32_t (*cheng_gui_host_contract_cheng_scene_media_es_set_paused_fn)(int32_t paused);
typedef int32_t (*cheng_gui_host_contract_cheng_scene_media_es_seek_to_position_ms_fn)(int32_t positionMs);

#ifdef __cplusplus
}
#endif

#endif /* CHENG_GUI_HOST_ADAPTER_CONTRACT_H */
