/* cold_type_identity_contract.h -- semantic TypeIdentity contract.
 *
 * This header contains compiler-semantic identity tags and hard admission
 * budgets only.  It is not a physical facts format or a wire schema.
 */

#ifndef COLD_TYPE_IDENTITY_CONTRACT_H
#define COLD_TYPE_IDENTITY_CONTRACT_H

enum {
    COLD_TYPE_IDENTITY_SCALAR         = 1,
    COLD_TYPE_IDENTITY_BORROW         = 2,
    COLD_TYPE_IDENTITY_SEQUENCE       = 3,
    COLD_TYPE_IDENTITY_FIXED_ARRAY    = 4,
    COLD_TYPE_IDENTITY_TUPLE          = 5,
    COLD_TYPE_IDENTITY_FUNCTION       = 6,
    COLD_TYPE_IDENTITY_OBJECT         = 7,
    COLD_TYPE_IDENTITY_REF_OBJECT     = 8,
    COLD_TYPE_IDENTITY_ENUM           = 9,
    COLD_TYPE_IDENTITY_APPLY          = 10,
    COLD_TYPE_IDENTITY_ALIAS          = 11,
    COLD_TYPE_IDENTITY_GENERIC_PARAM  = 12,
    COLD_TYPE_IDENTITY_OPTIONAL       = 13,
    COLD_TYPE_IDENTITY_SET            = 14,
    COLD_TYPE_IDENTITY_RAW_POINTER    = 15,
    COLD_TYPE_IDENTITY_GENERIC_BINDER = 16,
};

enum {
    COLD_GENERIC_BINDER_NONE = 0,
    COLD_GENERIC_BINDER_TYPE_ROW = 1,
    COLD_GENERIC_BINDER_OBJECT_ROW = 2,
    COLD_GENERIC_BINDER_FUNCTION_DECLARATION_ORIGIN = 3,
};

enum {
    COLD_TYPE_IDENTITY_DECLARATION_KIND_TYPE = 1,
    COLD_TYPE_IDENTITY_DECLARATION_KIND_OBJECT = 2,
    COLD_TYPE_IDENTITY_DECLARATION_KIND_FUNCTION = 3,
};

#define COLD_SEMANTIC_BUDGET_MAX_SOURCES   65536
#define COLD_SEMANTIC_BUDGET_MAX_FUNCTIONS 65536
#define COLD_TYPE_IDENTITY_BUDGET_MAX_CHILDREN 1000000

#endif /* COLD_TYPE_IDENTITY_CONTRACT_H */
