#!/usr/bin/env python3
"""semantic_gen: bounded semantic combination generator for Cheng compiler fixtures.

Generates <out>/<family>/s<seed>.cheng plus an ignition-matrix-isomorphic
<out>/matrix.json (name/tags/fixture + exactly one contract group per entry:
runtime expectRc, or expectCompileRc for diagnosed-rejection families).
Runnable directly by cheng_shape_matrix via its matrixPath parameter.

Discipline:
  - Deterministic: same (family set, seeds, root) => same bytes, always.
    Own xorshift64* PRNG; no wall clock, no dict-order dependence, no
    environment reads. --check regenerates in memory and byte-compares.
  - Oracle values are computed by the generator itself from the constants it
    emits (bounded semantics), never hand-recorded after the fact.
  - Diagnosed-rejection families (expectCompileRc=2) were verified to really
    bail on the reference drivers before their contract was encoded; see
    /Users/lbcheng/cheng-f24/diag_c1_semantic_gen/REPORT.md for evidence.

Usage:
  python3 tools/semantic_gen.py --root /abs/cheng/tree [--out fixtures/semantic]
      [--seeds 3] [--families all|name,name] [--check]

--root is mandatory: the matrix defaultRoot is filled from the caller, never
pinned inside the generator (clean-clone parameterization of the ignition
matrix.json defaultRoot problem).
"""

import argparse
import json
import os
import sys

MASK64 = (1 << 64) - 1

BANNER = "# generated by tools/semantic_gen.py -- deterministic; do not edit by hand\n"

FAMILIES = [
    "str_global_call_rhs",
    "slot_dedup_chain",
    "narrow_deref",
    "narrow_deref_fixed",
    "ref_seq_field",
    "agg_field_str_rhs",
    "addrof_scalar_root",
    "addrof_scalar_root_fixed",
    "int32_shell_shift",
    "borrowed_seq_bitcopy",
    "str_empty_eq",
    "neg_positional_ctor",
    "neg_seed_lint",
]

# battle-form tag -> matrix `form:` tag, per task_plan.md 2026-07-19 campaign names
FORM_TAG = {
    "str_global_call_rhs": "str-global-call-rhs",
    "slot_dedup_chain": "slot-dominance-dedup-chain",
    "narrow_deref": "narrow-deref",
    "narrow_deref_fixed": "narrow-deref-fixed-leg",
    "ref_seq_field": "ref-seq-field",
    "agg_field_str_rhs": "agg-field-str-rhs",
    "addrof_scalar_root": "addrof-scalar-root",
    "addrof_scalar_root_fixed": "addrof-scalar-root-fixed-leg",
    "int32_shell_shift": "int32-shell-shift",
    "borrowed_seq_bitcopy": "borrowed-seq-bitcopy",
    "str_empty_eq": "str-empty-eq",
    "neg_positional_ctor": "neg-positional-ctor",
    "neg_seed_lint": "neg-seed-lint",
}


def fnv1a64(text):
    h = 1469598103934665603
    for ch in text.encode("utf-8"):
        h ^= ch
        h = (h * 1099511628211) & MASK64
    return h


class Rng(object):
    """xorshift64* — stable across python versions and machines."""

    def __init__(self, seed):
        self.state = (seed ^ 0x9E3779B97F4A7C15) & MASK64 or 0x2545F4914F6CDD1D

    def next64(self):
        x = self.state
        x ^= (x >> 12) & MASK64
        x ^= (x << 25) & MASK64
        x ^= (x >> 27) & MASK64
        self.state = x & MASK64
        return (self.state * 2685821657736338717) & MASK64

    def below(self, n):
        return self.next64() % n

    def span(self, lo, hi):
        return lo + self.below(hi - lo + 1)


def rng_for(family, seed):
    return Rng((fnv1a64(family) << 1) ^ (seed * 0x100000001B3))


def word(rng, length):
    # lowercase letters only; fixture string literals stay pointer-safe
    return "".join(chr(ord("a") + rng.below(26)) for _ in range(length))


# ---------------------------------------------------------------- families
# every gen_<family>(seed) returns (source_text, contract_dict, note)


def gen_str_global_call_rhs(seed):
    """str global assigned from call RHS, reassigned, read back (I1/I3/B3 form)."""
    rng = rng_for("str_global_call_rhs", seed)
    length = rng.span(3, 9)
    cycles = rng.span(2, 3)
    text = word(rng, length)
    lines = [
        "var gCache: str",
        "",
        "fn makeStr(): str =",
        '    return "%s"' % text,
        "",
        "fn main(): int32 =",
    ]
    for i in range(cycles):
        lines.append("    gCache = makeStr()")
        lines.append("    let v%d = gCache" % i)
        lines.append("    if len(v%d) != %d:" % (i, length))
        lines.append("        return %d" % (90 + i))
    lines.append('    if v0 != "%s":' % text)
    lines.append("        return 95")
    lines.append("    return %s" % " + ".join("len(v%d)" % i for i in range(cycles)))
    expect = cycles * length
    note = ("str 全局 call-RHS: %d 次 `gCache = makeStr()` 写+全局读回, "
            "期望 rc=%d (cycles*len); 形态源=I1/I3 LocalStrTag 臂 + B3 模块级 str 缓存 idiom" % (cycles, expect))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": expect}, note


def gen_slot_dedup_chain(seed):
    """if-guarded tail call at return position; global counter makes any
    double physical execution directly observable in the exit code (T52 form)."""
    rng = rng_for("slot_dedup_chain", seed)
    k = rng.span(2, 9)
    n = rng.span(10, 60)
    threshold = rng.span(0, n - 1)
    chain = rng.span(1, 3)
    lines = [
        "var gCalls: int32",
        "",
        "fn helper(x: int32): int32 =",
        "    gCalls = gCalls + 1",
        "    return x + %d" % k,
        "",
        "fn bridge(v: int32): int32 =",
        "    if v > %d:" % threshold,
        "        return helper(v)",
        "    return v",
        "",
        "fn main(): int32 =",
    ]
    for i in range(chain):
        lines.append("    let r%d = bridge(%d)" % (i, n + i))
        lines.append("    if r%d != %d:" % (i, n + i + k))
        lines.append("        return %d" % (90 + i))
    lines.append("    return gCalls")
    note = ("槽支配 dedup 链: %d 次 bridge 尾部调用, helper 物理执行计数经全局可观测, "
            "期望 rc=%d (恰好 %d 次); 形态源=T52 return<call> fact dedup + I2 CFOS 槽支配" % (chain, chain, chain))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": chain}, note


def gen_narrow_deref(seed):
    """uint8 pointee deref: backend must emit a 1-byte load (ldrb), not 4B (W2C form)."""
    rng = rng_for("narrow_deref", seed)
    value = rng.span(10, 250)
    via_helper = rng.below(2) == 1
    lines = [
        "type",
        "    U8Ptr = uint8 *",
        "",
    ]
    if via_helper:
        lines += [
            "fn readByte(p: U8Ptr): uint8 =",
            "    return *p",
            "",
        ]
    lines += [
        "fn main(): int32 =",
        "    var b: uint8 = uint8(%d)" % value,
        "    let p: U8Ptr = U8Ptr(ptr(&b))",
    ]
    if via_helper:
        lines.append("    let v: uint8 = readByte(p)")
    else:
        lines.append("    let v: uint8 = *p")
    lines += [
        "    return int32(v)",
    ]
    note = ("窄 deref: uint8 pointee `*p` 必须发 1B 读, 期望 rc=%d; 形态源=W2C std/bytes.cheng:101 "
            "bufByteAt (I32PtrDerefPointerText 臂不看 pointee 宽度一律 4B); variant=%s" % (value, "helper" if via_helper else "direct"))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": value}, note


def gen_narrow_deref_fixed(seed):
    """legal-surface variant of narrow_deref: uint8 seq element read must emit a
    1-byte load (ldrb). 原族裸指针/解引用公开面已被 ZRPC 闸禁, 窄读判别形改经
    字节容器(uint8 序列)表达 — 元素读宽度看错即 4B 误读形态。"""
    rng = rng_for("narrow_deref_fixed", seed)
    a = rng.span(1, 120)
    b = rng.span(1, 120)
    via_helper = rng.below(2) == 1
    lines = []
    if via_helper:
        lines += [
            "fn byteAt(buf: uint8[], i: int32): uint8 =",
            "    return buf[i]",
            "",
        ]
    lines += [
        "fn main(): int32 =",
        "    var buf: uint8[]",
        "    add(buf, uint8(%d))" % a,
        "    add(buf, uint8(%d))" % b,
    ]
    if via_helper:
        lines.append("    let v0: uint8 = byteAt(buf, 0)")
    else:
        lines.append("    let v0: uint8 = buf[0]")
    lines += [
        "    if v0 != uint8(%d):" % a,
        "        return 71",
        "    if buf[1] != uint8(%d):" % b,
        "        return 72",
        "    return int32(v0) + int32(buf[1])",
    ]
    expect = a + b
    note = ("窄 deref 合法面变体(fixed-leg): uint8 序列元素读必须发 1B 读(ldrb), 期望 rc=%d (a+b); "
            "原族裸指针面已被 ZRPC 禁, 判别形改经字节容器; variant=%s" % (expect, "helper" if via_helper else "direct"))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": expect}, note


def gen_ref_seq_field(seed):
    """struct carrying a T[] field between two scalars: field offsets must treat
    the seq as a 16B inline header, not an 8B ref pointer (W2D form)."""
    rng = rng_for("ref_seq_field", seed)
    head = rng.span(3, 60)
    tail = rng.span(3, 60)
    nitems = rng.span(1, 3)
    tags = [rng.span(1, 9) for _ in range(nitems)]
    weights = [rng.span(1, 9) for _ in range(nitems)]
    lines = [
        "type",
        "    Sym =",
        "        tag: int32",
        "        weight: int32",
        "",
        "    Holder =",
        "        head: int32",
        "        items: Sym[]",
        "        tail: int32",
        "",
        "fn main(): int32 =",
        "    var h: Holder",
        "    h.head = %d" % head,
        "    h.tail = %d" % tail,
    ]
    for i in range(nitems):
        lines.append("    let s%d = Sym(tag: %d, weight: %d)" % (i, tags[i], weights[i]))
        lines.append("    add(h.items, s%d)" % i)
    checks = [("h.head", head, 81), ("h.tail", tail, 82), ("h.items.len", nitems, 83)]
    for expr, want, rc in checks:
        lines.append("    if %s != %d:" % (expr, want))
        lines.append("        return %d" % rc)
    for i in range(nitems):
        lines.append("    if h.items[%d].tag != %d:" % (i, tags[i]))
        lines.append("        return %d" % (84 + i * 2))
        lines.append("    if h.items[%d].weight != %d:" % (i, weights[i]))
        lines.append("        return %d" % (85 + i * 2))
    expect = head + tail
    lines.append("    return h.head + h.tail")
    note = ("ref-seq 字段: Holder{head, items:Sym[], tail} 偏移完整性, %d 元素入列后标量字段不得错位, "
            "期望 rc=%d; 形态源=W2D TypedExprIrAppendObjectTypeLayoutFromContext 把 Sym[] 错注 8B ref (正解 16B 内联 seq 头)" % (nitems, expect))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": expect}, note


def gen_agg_field_str_rhs(seed):
    """`strGlobal = agg.strField`: aggregate field str RHS must route to FieldLoad,
    never mint a never-written ghost slot (D3 form)."""
    rng = rng_for("agg_field_str_rhs", seed)
    length = rng.span(3, 9)
    num = rng.span(1, 40)
    extra = rng.below(2) == 1
    text = word(rng, length)
    fields = ["        name: str", "        n: int32"]
    ctor_args = ['name: "%s"' % text, "n: %d" % num]
    if extra:
        fields.append("        flag: bool")
        ctor_args.append("flag: true")
    lines = [
        "type",
        "    Cfg =",
    ] + fields + [
        "",
        "var gName: str",
        "",
        "fn main(): int32 =",
        "    let c = Cfg(%s)" % ", ".join(ctor_args),
        "    gName = c.name",
        "    if len(gName) != %d:" % length,
        "        return 71",
        "    if c.n != %d:" % num,
        "        return 72",
    ]
    if extra:
        lines.append("    if !c.flag:")
        lines.append("        return 73")
    expect = length + num
    lines.append("    return len(gName) + c.n")
    note = ("聚合字段 str RHS: `gName = c.name` 必须直连 FieldLoad, 期望 rc=%d (len+n); "
            "形态源=D3 全局 str 字段 RHS 幽灵槽 (gen3 mem_release/provider SIGSEGV/orbytes 同根); fields=%d" % (expect, 3 if extra else 2))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": expect}, note


def gen_addrof_scalar_root(seed):
    """ptr(&scalar) deref store + readback: address-of a scalar root must
    materialize a real pointer (R1/D2 + G4 family form)."""
    rng = rng_for("addrof_scalar_root", seed)
    value = rng.span(1, 250)
    via_var = rng.below(2) == 1
    lines = [
        "type",
        "    Int32Ptr = int32 *",
        "",
        "fn main(): int32 =",
        "    var x: int32",
    ]
    if via_var:
        lines.append("    let value: int32 = %d" % value)
    lines.append("    let target: Int32Ptr = Int32Ptr(ptr(&x))")
    lines.append("    *target = %s" % ("value" if via_var else str(value)))
    lines.append("    if x != %d:" % value)
    lines.append("        return 81")
    lines.append("    return x")
    note = ("AddrOf 标量根: `ptr(&x)` 物化真指针后 `*p = %s` + 读回, 期望 rc=%d; "
            "形态源=R1/D2 AddrOfPlaceRootInfo 标量根 + G4 bareptr deref-store" % ("局部变量" if via_var else "常量", value))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": value}, note


def gen_addrof_scalar_root_fixed(seed):
    """legal-surface variant of addrof_scalar_root: `&place`(标量根/字段取址实参)
    必须物化真地址 — 经 std.atomic 的 `&c.value` 形写/RMW 后, 根字段直读回
    (写未落地即原族同款红码 81)。原族 ptr() 裸指针面已被 ZRPC 闸禁,
    `&Identifier/&Field` 为收窄后合法面(parser &place 闸)。"""
    rng = rng_for("addrof_scalar_root_fixed", seed)
    value = rng.span(1, 250)
    via_rmw = rng.below(2) == 1
    lines = [
        "import std/atomic",
        "",
        "fn main(): int32 =",
        "    var c = atomic.NewI32(0)",
    ]
    if via_rmw:
        lines.append("    let prev: int32 = atomic.FetchAddI32(c, %d)" % value)
        lines.append("    if prev != 0:")
        lines.append("        return 80")
    else:
        lines.append("    atomic.StoreI32(c, %d)" % value)
    lines.append("    if c.value != %d:" % value)
    lines.append("        return 81")
    lines.append("    return c.value")
    note = ("AddrOf 标量根合法面变体(fixed-leg): `&c.value` 物化真地址后经原子%s写, 根字段直读回, "
            "期望 rc=%d; 形态源=R1/D2 AddrOfPlaceRootInfo 标量根(收窄后 `&place` 合法面)" % ("RMW " if via_rmw else "", value))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": value}, note


def gen_int32_shell_shift(seed):
    """int32(int64(x) >> s) with s > 32: the shift arm must honor the 64-bit
    operand width (a 32-bit asr silently reduces the amount mod 32) (D1 form)."""
    rng = rng_for("int32_shell_shift", seed)
    want = rng.span(3, 250)
    shift = rng.span(33, 40)
    low = rng.span(0, (1 << 20) - 1)
    base = (want << shift) | low
    nested = rng.below(2) == 1
    lines = [
        "fn main(): int32 =",
        "    var x: int64 = Int64(%d)" % base,
    ]
    if nested:
        s1 = shift // 2 + 1
        s2 = shift - s1
        # recompute so the composed shift lands exactly on `want`
        lines.append("    let y: int32 = int32((x >> %d) >> %d)" % (s1, s2))
        lines.append("    return y")
        note = ("Int32 壳移位(嵌套): int32((x>>%d)>>%d) 合成 64 位右移 %d, 期望 rc=%d; "
                "形态源=D1 标量移位臂硬编 i32 Asr 不看操作数宽度" % (s1, s2, shift, want))
    else:
        lines.append("    let y: int32 = int32(x >> %d)" % shift)
        lines.append("    return y")
        note = ("Int32 壳移位: int32(Int64(%d) >> %d) 期望 rc=%d; "
                "形态源=D1 (32 位 asr 会把移位量 mod 32, 本族移位量全部 >32)" % (base, shift, want))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": want}, note


def gen_neg_positional_ctor(seed):
    """positional-arg ctor call: no valid emit exists; the compiler must reject
    (diagnosed rejection), never silently emit."""
    rng = rng_for("neg_positional_ctor", seed)
    a = rng.span(1, 99)
    b = rng.span(1, 99)
    lines = [
        "type",
        "    Pair =",
        "        a: int32",
        "        b: int32",
        "",
        "fn main(): int32 =",
        "    var x = Pair(%d, %d)" % (a, b),
        "    return x.a",
    ]
    note = ("负例: 位置实参构造器 Pair(%d, %d) 必须被诊断拒绝 compile rc=2 (fam_7/ctor-positional-real-emit 同族); "
            "两参考 driver 均实证拒绝" % (a, b))
    return BANNER + "\n".join(lines) + "\n", {"expectCompileRc": 2}, note


def gen_neg_seed_lint(seed):
    """function-local integer decl with redundant explicit `= 0`: accepted by
    stage3, rejected by the self-hosted driver (tools/seed_lint_check.sh gate)."""
    rng = rng_for("neg_seed_lint", seed)
    name = "v%d" % rng.span(0, 999)
    lines = [
        "fn main(): int32 =",
        "    var %s: int32 = 0" % name,
        "    return %s" % name,
    ]
    note = ("负例: `var %s: int32 = 0` 冗余显式零初始化, 自举 driver 诊断拒绝 compile rc=2 "
            "(seed_lint 门); 冷金标 cheng.stage3 接受此形(rc=0)——已知 driver 间口径差, 非缺陷" % name)
    return BANNER + "\n".join(lines) + "\n", {"expectCompileRc": 2}, note


def gen_borrowed_seq_bitcopy(seed):
    """call-returned seq stored to a global then appended/read: the header must be
    owned-copied into the global (borrowed flags=0 header must never reach release
    or realloc with the callee's dead buffer) (form68 importedModules fill form)."""
    rng = rng_for("borrowed_seq_bitcopy", seed)
    n0 = rng.span(2, 4)
    vals = [rng.span(1, 60) for _ in range(4)]
    double = rng.below(2) == 1
    lines = [
        "fn makeSeq(): int32[] =",
        "    return [%s]" % ", ".join(str(v) for v in vals[:n0]),
        "",
        "var g: int32[]",
        "",
        "fn main(): int32 =",
        "    g = makeSeq()",
    ]
    if double:
        lines.append("    g = makeSeq()")
    lines.append("    add(g, %d)" % vals[3])
    lines.append("    if g.len != %d:" % (n0 + 1))
    lines.append("        return 71")
    lines.append("    if g[%d] != %d:" % (n0, vals[3]))
    lines.append("        return 72")
    total = n0 + 1 + vals[3]
    lines.append("    return g.len + g[%d]" % n0)
    note = ("借来 seq 头位拷贝: g = makeSeq()%s 后 add(g, %d) 追加并读回, "
            "全局槽必须 owned-copy 16B seq 头(借来 flags=0 不得在覆盖/追加时触碰释放), "
            "期望 rc=%d (len+尾值); 形态源=importedModules 类填充位拷贝幽灵 borrowed" % (
                " ×2(覆盖借来头)" if double else "", vals[3], total))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": total}, note


def gen_str_empty_eq(seed):
    """str field compared against \"\": the comparison must dispatch on len
    (zero), never on the field buffer's stack address or the literal's address
    (form69 str-field-empty-eq form)."""
    rng = rng_for("str_empty_eq", seed)
    text = word(rng, rng.span(3, 8))
    n = rng.span(1, 40)
    via_assign = rng.below(2) == 1
    lines = [
        "type",
        "    Cfg =",
        "        name: str",
        "        n: int32",
        "",
        "fn main(): int32 =",
    ]
    if via_assign:
        lines.append('    var c = Cfg(name: "%s", n: %d)' % (text, n))
        lines.append('    c.name = ""')
    else:
        lines.append('    var c = Cfg(name: "", n: %d)' % n)
    lines.append('    if c.name != "":')
    lines.append("        return 71")
    lines.append('    c.name = "%s"' % text)
    lines.append('    if c.name == "":')
    lines.append("        return 72")
    expect = len(text) + n
    lines.append("    return len(c.name) + c.n")
    note = ("str==\"\" 空串比较: str 字段(%s)==\"\" 必须按 len==0 判定, 不得比栈/字面量地址, "
            "空与非空两方向都断言, 期望 rc=%d (len+n); 形态源=D3 字段空串比较地址误判" % (
                "赋空后" if via_assign else "直构", expect))
    return BANNER + "\n".join(lines) + "\n", {"expectRc": expect}, note


GENS = {
    "str_global_call_rhs": gen_str_global_call_rhs,
    "slot_dedup_chain": gen_slot_dedup_chain,
    "narrow_deref": gen_narrow_deref,
    "narrow_deref_fixed": gen_narrow_deref_fixed,
    "ref_seq_field": gen_ref_seq_field,
    "agg_field_str_rhs": gen_agg_field_str_rhs,
    "addrof_scalar_root": gen_addrof_scalar_root,
    "addrof_scalar_root_fixed": gen_addrof_scalar_root_fixed,
    "int32_shell_shift": gen_int32_shell_shift,
    "borrowed_seq_bitcopy": gen_borrowed_seq_bitcopy,
    "str_empty_eq": gen_str_empty_eq,
    "neg_positional_ctor": gen_neg_positional_ctor,
    "neg_seed_lint": gen_neg_seed_lint,
}


def build(root, out_rel, families, seeds):
    """Returns {relpath: bytes} for the whole fixture set + matrix.json."""
    files = {}
    entries = []
    for family in families:
        gen = GENS[family]
        for seed in range(1, seeds + 1):
            source, contract, note = gen(seed)
            name = "%s_s%d" % (family, seed)
            rel = "%s/%s.cheng" % (family, name)
            files[rel] = source.encode("utf-8")
            entry = {
                "name": name,
                "tags": ["generated", "family:%s" % family, "form:%s" % FORM_TAG[family], "seed:%d" % seed],
                "fixture": rel,
            }
            entry.update(contract)
            entry["note"] = note
            entries.append(entry)
    matrix = {
        "defaultRoot": root,
        "generatedBy": "tools/semantic_gen.py (deterministic; regenerate with same --root/--seeds to reproduce byte-identical output)",
        "entries": entries,
    }
    text = json.dumps(matrix, ensure_ascii=False, indent=2) + "\n"
    files["matrix.json"] = text.encode("utf-8")
    return files


def main(argv):
    parser = argparse.ArgumentParser(description="bounded semantic combination generator for Cheng fixtures")
    parser.add_argument("--root", required=True, help="absolute Cheng tree root; written into matrix.json defaultRoot (never pinned by the generator)")
    parser.add_argument("--out", default="fixtures/semantic", help="output dir, relative to cheng-fusion package root (default fixtures/semantic)")
    parser.add_argument("--seeds", type=int, default=3, help="seeds per family, seeds are 1..N (default 3)")
    parser.add_argument("--families", default="all", help="comma list, or 'all' (default)")
    parser.add_argument("--check", action="store_true", help="regenerate in memory and byte-compare against --out; rc=1 on any drift, writes nothing")
    args = parser.parse_args(argv)

    root = os.path.realpath(args.root)
    if not os.path.isdir(root):
        parser.error("--root is not a directory: %s" % root)
    if args.seeds < 1:
        parser.error("--seeds must be >= 1")
    if args.families == "all":
        families = list(FAMILIES)
    else:
        families = args.families.split(",")
        unknown = [f for f in families if f not in GENS]
        if unknown:
            parser.error("unknown families: %s (known: %s)" % (",".join(unknown), ",".join(FAMILIES)))

    package_root = os.path.realpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    out_dir = args.out if os.path.isabs(args.out) else os.path.join(package_root, args.out)

    files = build(root, args.out, families, args.seeds)

    if args.check:
        drift = []
        for rel in sorted(files):
            path = os.path.join(out_dir, rel)
            if not os.path.isfile(path):
                drift.append("missing: %s" % rel)
                continue
            with open(path, "rb") as fh:
                if fh.read() != files[rel]:
                    drift.append("drifted: %s" % rel)
        extra = []
        managed_dirs = set(FAMILIES)
        for dirpath, _dirnames, filenames in os.walk(out_dir):
            for fn in filenames:
                rel = os.path.relpath(os.path.join(dirpath, fn), out_dir)
                # 只审计生成器自管范围(family 目录与 matrix.json); 其他生成器
                # (如 grammar_corpus_gen.ts)共享 fixtures/semantic, 不算漂移。
                if rel == "matrix.json" or rel.split(os.sep)[0] in managed_dirs:
                    if rel not in files and not fn.startswith("."):
                        extra.append("extra: %s" % rel)
        problems = drift + extra
        if problems:
            sys.stderr.write("semantic_gen --check FAIL (%d):\n%s\n" % (len(problems), "\n".join(problems)))
            return 1
        sys.stdout.write("semantic_gen --check OK: %d files byte-identical (root=%s seeds=%d families=%d)\n" % (len(files), root, args.seeds, len(families)))
        return 0

    written = []
    for rel in sorted(files):
        path = os.path.join(out_dir, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as fh:
            fh.write(files[rel])
        written.append(rel)
    sys.stdout.write("semantic_gen: wrote %d files under %s (root=%s, %d families x %d seeds = %d fixtures)\n"
                     % (len(written), out_dir, root, len(families), args.seeds, len(written) - 1))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
